// src/tools/drum-synth/index.tsx
'use client';

import { useEffect, useRef, useCallback, useState } from 'react';
import { Volume2, Play } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';
import { registerTool } from '../registry';
import type { ToolDefinition, ToolProps } from '../types';
import { cn } from '@/lib/utils';

// ========================================
// Drum Synth Tool - 드럼 신디사이저
// ========================================

interface DrumParams {
  pitch: number;
  decay: number;
  tone: number;
  snap: number;
}

export interface DrumSynthSettings {
  kick: DrumParams;
  snare: DrumParams;
  hihat: DrumParams;
  tom: DrumParams;
  volume: number;
  selectedDrum: 'kick' | 'snare' | 'hihat' | 'tom';
  [key: string]: unknown;
}

const defaultSettings: DrumSynthSettings = {
  kick: { pitch: 60, decay: 0.5, tone: 50, snap: 30 },
  snare: { pitch: 200, decay: 0.2, tone: 70, snap: 80 },
  hihat: { pitch: 800, decay: 0.05, tone: 90, snap: 10 },
  tom: { pitch: 120, decay: 0.3, tone: 40, snap: 20 },
  volume: 0.7,
  selectedDrum: 'kick',
};

const DRUMS = [
  { id: 'kick', name: 'Kick', icon: '🔴' },
  { id: 'snare', name: 'Snare', icon: '🟡' },
  { id: 'hihat', name: 'Hi-Hat', icon: '🟢' },
  { id: 'tom', name: 'Tom', icon: '🔵' },
] as const;

function DrumSynthComponent({
  settings,
  onSettingsChange,
}: ToolProps<DrumSynthSettings>) {
  const audioContextRef = useRef<AudioContext | null>(null);
  const [isTriggering, setIsTriggering] = useState<string | null>(null);

  const { volume, selectedDrum } = settings;
  const drumParams = settings[selectedDrum] as DrumParams;

  // Initialize AudioContext
  useEffect(() => {
    audioContextRef.current = new AudioContext();
    return () => {
      audioContextRef.current?.close();
    };
  }, []);

  // Play drum sound
  const playDrum = useCallback(
    (drumId: 'kick' | 'snare' | 'hihat' | 'tom') => {
      const ctx = audioContextRef.current;
      if (!ctx) return;

      if (ctx.state === 'suspended') {
        ctx.resume();
      }

      const params = settings[drumId] as DrumParams;
      const time = ctx.currentTime;

      // Main oscillator
      const osc = ctx.createOscillator();
      const oscGain = ctx.createGain();
      const filter = ctx.createBiquadFilter();

      osc.connect(filter);
      filter.connect(oscGain);
      oscGain.connect(ctx.destination);

      // Configure based on drum type
      if (drumId === 'kick') {
        osc.frequency.setValueAtTime(params.pitch * 2, time);
        osc.frequency.exponentialRampToValueAtTime(params.pitch, time + 0.05);
        osc.type = 'sine';
        filter.type = 'lowpass';
        filter.frequency.value = 200 + params.tone * 3;
      } else if (drumId === 'snare') {
        osc.frequency.value = params.pitch;
        osc.type = 'triangle';
        filter.type = 'highpass';
        filter.frequency.value = params.tone * 5;

        // Noise for snare
        const bufferSize = ctx.sampleRate * params.decay;
        const noiseBuffer = ctx.createBuffer(1, bufferSize, ctx.sampleRate);
        const output = noiseBuffer.getChannelData(0);
        for (let i = 0; i < bufferSize; i++) {
          output[i] = Math.random() * 2 - 1;
        }

        const noise = ctx.createBufferSource();
        const noiseGain = ctx.createGain();
        const noiseFilter = ctx.createBiquadFilter();

        noise.buffer = noiseBuffer;
        noise.connect(noiseFilter);
        noiseFilter.connect(noiseGain);
        noiseGain.connect(ctx.destination);

        noiseFilter.type = 'bandpass';
        noiseFilter.frequency.value = 1000 + params.tone * 30;

        noiseGain.gain.setValueAtTime(volume * (params.snap / 100), time);
        noiseGain.gain.exponentialRampToValueAtTime(0.01, time + params.decay);

        noise.start(time);
        noise.stop(time + params.decay);
      } else if (drumId === 'hihat') {
        osc.frequency.value = params.pitch;
        osc.type = 'square';
        filter.type = 'highpass';
        filter.frequency.value = 5000 + params.tone * 50;
      } else {
        // Tom
        osc.frequency.setValueAtTime(params.pitch * 1.5, time);
        osc.frequency.exponentialRampToValueAtTime(params.pitch, time + 0.02);
        osc.type = 'sine';
        filter.type = 'lowpass';
        filter.frequency.value = 500 + params.tone * 10;
      }

      oscGain.gain.setValueAtTime(volume, time);
      oscGain.gain.exponentialRampToValueAtTime(0.01, time + params.decay);

      osc.start(time);
      osc.stop(time + params.decay);

      // Visual feedback
      setIsTriggering(drumId);
      setTimeout(() => setIsTriggering(null), 100);
    },
    [settings, volume]
  );

  // Update drum parameter
  const updateParam = (param: keyof DrumParams, value: number) => {
    onSettingsChange({
      [selectedDrum]: {
        ...drumParams,
        [param]: value,
      },
    });
  };

  return (
    <div className="flex h-full flex-col gap-4 p-4">
      {/* Drum Pads */}
      <div className="grid grid-cols-4 gap-2">
        {DRUMS.map((drum) => (
          <button
            key={drum.id}
            onClick={() => playDrum(drum.id)}
            onMouseDown={() => onSettingsChange({ selectedDrum: drum.id })}
            className={cn(
              'flex h-20 flex-col items-center justify-center rounded-lg border-2 transition-all',
              selectedDrum === drum.id
                ? 'border-primary bg-primary/10'
                : 'border-muted bg-muted/50 hover:bg-muted',
              isTriggering === drum.id && 'scale-95 bg-primary/30'
            )}
          >
            <span className="text-2xl">{drum.icon}</span>
            <span className="text-xs font-medium">{drum.name}</span>
          </button>
        ))}
      </div>

      {/* Parameter Controls */}
      <div className="flex-1 rounded-lg border bg-card p-4">
        <h3 className="mb-4 text-sm font-semibold">
          {DRUMS.find((d) => d.id === selectedDrum)?.name} Parameters
        </h3>

        <div className="grid gap-4">
          <div className="grid gap-2">
            <div className="flex items-center justify-between">
              <span className="text-sm">Pitch</span>
              <span className="text-xs text-muted-foreground">
                {drumParams.pitch} Hz
              </span>
            </div>
            <Slider
              value={[drumParams.pitch]}
              onValueChange={([v]) => updateParam('pitch', v)}
              min={20}
              max={1000}
              step={1}
            />
          </div>

          <div className="grid gap-2">
            <div className="flex items-center justify-between">
              <span className="text-sm">Decay</span>
              <span className="text-xs text-muted-foreground">
                {(drumParams.decay * 1000).toFixed(0)} ms
              </span>
            </div>
            <Slider
              value={[drumParams.decay * 1000]}
              onValueChange={([v]) => updateParam('decay', v / 1000)}
              min={10}
              max={1000}
              step={10}
            />
          </div>

          <div className="grid gap-2">
            <div className="flex items-center justify-between">
              <span className="text-sm">Tone</span>
              <span className="text-xs text-muted-foreground">
                {drumParams.tone}%
              </span>
            </div>
            <Slider
              value={[drumParams.tone]}
              onValueChange={([v]) => updateParam('tone', v)}
              min={0}
              max={100}
            />
          </div>

          <div className="grid gap-2">
            <div className="flex items-center justify-between">
              <span className="text-sm">Snap/Noise</span>
              <span className="text-xs text-muted-foreground">
                {drumParams.snap}%
              </span>
            </div>
            <Slider
              value={[drumParams.snap]}
              onValueChange={([v]) => updateParam('snap', v)}
              min={0}
              max={100}
            />
          </div>
        </div>
      </div>

      {/* Master Volume */}
      <div className="flex items-center gap-3 rounded-lg border bg-card p-3">
        <Volume2 className="h-4 w-4 text-muted-foreground" />
        <Slider
          value={[volume * 100]}
          onValueChange={([v]) => onSettingsChange({ volume: v / 100 })}
          max={100}
          className="flex-1"
        />
        <span className="w-10 text-right text-xs text-muted-foreground">
          {Math.round(volume * 100)}%
        </span>
      </div>

      {/* Play Button */}
      <Button
        onClick={() => playDrum(selectedDrum)}
        size="lg"
        className="w-full"
      >
        <Play className="mr-2 h-5 w-5" />
        Play {DRUMS.find((d) => d.id === selectedDrum)?.name}
      </Button>
    </div>
  );
}

// Tool Definition
export const drumSynthTool: ToolDefinition<DrumSynthSettings> = {
  meta: {
    id: 'drum-synth',
    name: {
      ko: '드럼 신스',
      en: 'Drum Synth',
    },
    description: {
      ko: '파라미터 조절 가능한 드럼 사운드 합성',
      en: 'Synthesize drum sounds with adjustable parameters',
    },
    icon: '🎛️',
    category: 'music',
    defaultSize: 'md',
    minSize: { width: 300, height: 400 },
    tags: ['drums', 'synthesizer', 'sound-design'],
  },
  defaultSettings,
  component: DrumSynthComponent,
};

// Auto-register
registerTool(drumSynthTool);

// src/apps/drum-synth/components/DrumSynth.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';
  import { t } from '../../../stores';
  import './DrumSynth.css';

  let audioContext: AudioContext | null = null;

  $: drumSynth = $t.drumSynth;

  // Selected drum type
  type DrumType = 'kick' | 'snare' | 'hihat' | 'clap';
  let selectedDrum: DrumType = 'kick';
  let playingDrum: DrumType | null = null;

  // Parameters for each drum type
  let kickParams = { pitchStart: 150, pitchEnd: 40, pitchDecay: 0.1, ampDecay: 0.3, volume: 80 };
  let snareParams = { toneFreq: 200, toneDecay: 0.1, noiseDecay: 0.15, volume: 80 };
  let hihatParams = { filterFreq: 8000, decay: 0.05, volume: 60 };
  let clapParams = { filterFreq: 1000, decay: 0.1, spread: 0.02, volume: 70 };

  const drumTypes: DrumType[] = ['kick', 'snare', 'hihat', 'clap'];

  function initAudio() {
    if (!audioContext) {
      audioContext = new (window.AudioContext || (window as any).webkitAudioContext)();
    }
    return audioContext;
  }

  function playKick() {
    const ctx = initAudio();
    if (ctx.state === 'suspended') ctx.resume();
    const osc = ctx.createOscillator();
    const gain = ctx.createGain();

    osc.connect(gain);
    gain.connect(ctx.destination);

    osc.frequency.setValueAtTime(kickParams.pitchStart, ctx.currentTime);
    osc.frequency.exponentialRampToValueAtTime(kickParams.pitchEnd, ctx.currentTime + kickParams.pitchDecay);
    gain.gain.setValueAtTime(kickParams.volume / 100, ctx.currentTime);
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + kickParams.ampDecay);
    osc.type = 'sine';

    osc.start(ctx.currentTime);
    osc.stop(ctx.currentTime + kickParams.ampDecay);
  }

  function playSnare() {
    const ctx = initAudio();
    if (ctx.state === 'suspended') ctx.resume();

    // Tone component
    const osc = ctx.createOscillator();
    const oscGain = ctx.createGain();
    osc.connect(oscGain);
    oscGain.connect(ctx.destination);
    osc.frequency.value = snareParams.toneFreq;
    oscGain.gain.setValueAtTime(snareParams.volume / 200, ctx.currentTime);
    oscGain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + snareParams.toneDecay);
    osc.type = 'triangle';
    osc.start(ctx.currentTime);
    osc.stop(ctx.currentTime + snareParams.toneDecay);

    // Noise component
    const buffer = ctx.createBuffer(1, ctx.sampleRate * snareParams.noiseDecay, ctx.sampleRate);
    const data = buffer.getChannelData(0);
    for (let i = 0; i < buffer.length; i++) {
      data[i] = Math.random() * 2 - 1;
    }
    const source = ctx.createBufferSource();
    source.buffer = buffer;
    const noiseGain = ctx.createGain();
    source.connect(noiseGain);
    noiseGain.connect(ctx.destination);
    noiseGain.gain.setValueAtTime(snareParams.volume / 100, ctx.currentTime);
    noiseGain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + snareParams.noiseDecay);
    source.start(ctx.currentTime);
  }

  function playHihat() {
    const ctx = initAudio();
    if (ctx.state === 'suspended') ctx.resume();

    const buffer = ctx.createBuffer(1, ctx.sampleRate * hihatParams.decay, ctx.sampleRate);
    const data = buffer.getChannelData(0);
    for (let i = 0; i < buffer.length; i++) {
      data[i] = (Math.random() * 2 - 1) * Math.exp(-i / (ctx.sampleRate * 0.05));
    }
    const source = ctx.createBufferSource();
    source.buffer = buffer;
    const gain = ctx.createGain();
    const filter = ctx.createBiquadFilter();
    filter.type = 'highpass';
    filter.frequency.value = hihatParams.filterFreq;
    source.connect(filter);
    filter.connect(gain);
    gain.connect(ctx.destination);
    gain.gain.setValueAtTime(hihatParams.volume / 100, ctx.currentTime);
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + hihatParams.decay);
    source.start(ctx.currentTime);
  }

  function playClap() {
    const ctx = initAudio();
    if (ctx.state === 'suspended') ctx.resume();

    const buffer = ctx.createBuffer(1, ctx.sampleRate * clapParams.decay, ctx.sampleRate);
    const data = buffer.getChannelData(0);
    for (let i = 0; i < buffer.length; i++) {
      data[i] = Math.random() * 2 - 1;
    }
    const source = ctx.createBufferSource();
    source.buffer = buffer;
    const gain = ctx.createGain();
    const filter = ctx.createBiquadFilter();
    filter.type = 'bandpass';
    filter.frequency.value = clapParams.filterFreq;
    filter.Q.value = 1;
    source.connect(filter);
    filter.connect(gain);
    gain.connect(ctx.destination);
    gain.gain.setValueAtTime(clapParams.volume / 100, ctx.currentTime);
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + clapParams.decay);
    source.start(ctx.currentTime);
  }

  function playDrum(type: DrumType) {
    playingDrum = type;
    setTimeout(() => playingDrum = null, 100);

    switch (type) {
      case 'kick': playKick(); break;
      case 'snare': playSnare(); break;
      case 'hihat': playHihat(); break;
      case 'clap': playClap(); break;
    }
  }

  function getDrumLabel(type: DrumType): string {
    return drumSynth[type] || type;
  }

  function resetParams() {
    switch (selectedDrum) {
      case 'kick':
        kickParams = { pitchStart: 150, pitchEnd: 40, pitchDecay: 0.1, ampDecay: 0.3, volume: 80 };
        break;
      case 'snare':
        snareParams = { toneFreq: 200, toneDecay: 0.1, noiseDecay: 0.15, volume: 80 };
        break;
      case 'hihat':
        hihatParams = { filterFreq: 8000, decay: 0.05, volume: 60 };
        break;
      case 'clap':
        clapParams = { filterFreq: 1000, decay: 0.1, spread: 0.02, volume: 70 };
        break;
    }
  }

  onDestroy(() => {
    if (audioContext) {
      audioContext.close();
    }
  });
</script>

<div class="drum-synth">
  <!-- Quick Play Pads -->
  <div class="synth-pads">
    <span class="synth-pads-label">{drumSynth.quickPlay}</span>
    <div class="synth-pads-grid">
      {#each drumTypes as type}
        <button
          class="synth-pad"
          class:synth-pad--playing={playingDrum === type}
          on:click={() => playDrum(type)}
        >
          {getDrumLabel(type)}
        </button>
      {/each}
    </div>
  </div>

  <!-- Drum Type Selector -->
  <div class="synth-selector">
    {#each drumTypes as type}
      <button
        class="synth-drum-btn"
        class:synth-drum-btn--selected={selectedDrum === type}
        on:click={() => selectedDrum = type}
      >
        {getDrumLabel(type)}
      </button>
    {/each}
  </div>

  <!-- Parameters Section -->
  <div class="synth-content">
    <div class="synth-params">
      <div class="synth-params-header">
        <h3 class="synth-params-title">{getDrumLabel(selectedDrum)} {drumSynth.parameters}</h3>
        <button class="synth-reset-btn" on:click={resetParams} aria-label="Reset">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8" />
            <path d="M3 3v5h5" />
          </svg>
        </button>
      </div>

      <div class="synth-params-grid">
        {#if selectedDrum === 'kick'}
          <div class="synth-param">
            <div class="synth-param-header">
              <span class="synth-param-label">{drumSynth.pitchStart}</span>
              <span class="synth-param-value">{kickParams.pitchStart} Hz</span>
            </div>
            <div class="synth-param-slider-wrap">
              <input type="range" class="synth-param-slider" min="50" max="300" bind:value={kickParams.pitchStart} />
            </div>
          </div>
          <div class="synth-param">
            <div class="synth-param-header">
              <span class="synth-param-label">{drumSynth.pitchEnd}</span>
              <span class="synth-param-value">{kickParams.pitchEnd} Hz</span>
            </div>
            <div class="synth-param-slider-wrap">
              <input type="range" class="synth-param-slider" min="20" max="100" bind:value={kickParams.pitchEnd} />
            </div>
          </div>
          <div class="synth-param">
            <div class="synth-param-header">
              <span class="synth-param-label">{drumSynth.ampDecay}</span>
              <span class="synth-param-value">{kickParams.ampDecay.toFixed(2)}s</span>
            </div>
            <div class="synth-param-slider-wrap">
              <input type="range" class="synth-param-slider" min="0.1" max="1" step="0.05" bind:value={kickParams.ampDecay} />
            </div>
          </div>
          <div class="synth-param">
            <div class="synth-param-header">
              <span class="synth-param-label">{drumSynth.volume}</span>
              <span class="synth-param-value">{kickParams.volume}%</span>
            </div>
            <div class="synth-param-slider-wrap">
              <input type="range" class="synth-param-slider" min="0" max="100" bind:value={kickParams.volume} />
            </div>
          </div>
        {:else if selectedDrum === 'snare'}
          <div class="synth-param">
            <div class="synth-param-header">
              <span class="synth-param-label">{drumSynth.toneFreq}</span>
              <span class="synth-param-value">{snareParams.toneFreq} Hz</span>
            </div>
            <div class="synth-param-slider-wrap">
              <input type="range" class="synth-param-slider" min="100" max="400" bind:value={snareParams.toneFreq} />
            </div>
          </div>
          <div class="synth-param">
            <div class="synth-param-header">
              <span class="synth-param-label">{drumSynth.noiseDecay}</span>
              <span class="synth-param-value">{snareParams.noiseDecay.toFixed(2)}s</span>
            </div>
            <div class="synth-param-slider-wrap">
              <input type="range" class="synth-param-slider" min="0.05" max="0.5" step="0.01" bind:value={snareParams.noiseDecay} />
            </div>
          </div>
          <div class="synth-param">
            <div class="synth-param-header">
              <span class="synth-param-label">{drumSynth.volume}</span>
              <span class="synth-param-value">{snareParams.volume}%</span>
            </div>
            <div class="synth-param-slider-wrap">
              <input type="range" class="synth-param-slider" min="0" max="100" bind:value={snareParams.volume} />
            </div>
          </div>
        {:else if selectedDrum === 'hihat'}
          <div class="synth-param">
            <div class="synth-param-header">
              <span class="synth-param-label">{drumSynth.filterFreq}</span>
              <span class="synth-param-value">{hihatParams.filterFreq} Hz</span>
            </div>
            <div class="synth-param-slider-wrap">
              <input type="range" class="synth-param-slider" min="4000" max="12000" bind:value={hihatParams.filterFreq} />
            </div>
          </div>
          <div class="synth-param">
            <div class="synth-param-header">
              <span class="synth-param-label">{drumSynth.decay}</span>
              <span class="synth-param-value">{hihatParams.decay.toFixed(2)}s</span>
            </div>
            <div class="synth-param-slider-wrap">
              <input type="range" class="synth-param-slider" min="0.01" max="0.2" step="0.01" bind:value={hihatParams.decay} />
            </div>
          </div>
          <div class="synth-param">
            <div class="synth-param-header">
              <span class="synth-param-label">{drumSynth.volume}</span>
              <span class="synth-param-value">{hihatParams.volume}%</span>
            </div>
            <div class="synth-param-slider-wrap">
              <input type="range" class="synth-param-slider" min="0" max="100" bind:value={hihatParams.volume} />
            </div>
          </div>
        {:else if selectedDrum === 'clap'}
          <div class="synth-param">
            <div class="synth-param-header">
              <span class="synth-param-label">{drumSynth.filterFreq}</span>
              <span class="synth-param-value">{clapParams.filterFreq} Hz</span>
            </div>
            <div class="synth-param-slider-wrap">
              <input type="range" class="synth-param-slider" min="500" max="2000" bind:value={clapParams.filterFreq} />
            </div>
          </div>
          <div class="synth-param">
            <div class="synth-param-header">
              <span class="synth-param-label">{drumSynth.decay}</span>
              <span class="synth-param-value">{clapParams.decay.toFixed(2)}s</span>
            </div>
            <div class="synth-param-slider-wrap">
              <input type="range" class="synth-param-slider" min="0.05" max="0.3" step="0.01" bind:value={clapParams.decay} />
            </div>
          </div>
          <div class="synth-param">
            <div class="synth-param-header">
              <span class="synth-param-label">{drumSynth.volume}</span>
              <span class="synth-param-value">{clapParams.volume}%</span>
            </div>
            <div class="synth-param-slider-wrap">
              <input type="range" class="synth-param-slider" min="0" max="100" bind:value={clapParams.volume} />
            </div>
          </div>
        {/if}
      </div>
    </div>

    <!-- Play Button -->
    <div class="synth-play-section">
      <button
        class="synth-play-btn"
        class:synth-play-btn--playing={playingDrum === selectedDrum}
        on:click={() => playDrum(selectedDrum)}
      >
        <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
          <polygon points="5 3 19 12 5 21 5 3" />
        </svg>
        <span>{drumSynth.play}</span>
      </button>
    </div>
  </div>
</div>
