// src/standalone/qr/QRGenerator.tsx
import { useState, useEffect, memo, useCallback, useMemo } from 'react';
import QRious from 'qrious';
import type { Translations } from './i18n';

const QR_SIZE = 1024;
const URL_DEBOUNCE_MS = 300;
const COLOR_THRESHOLD = { BLACK: 50, WHITE: 200 };
const TIMEOUTS = { DOWNLOAD_CLEANUP: 100, COPY_SUCCESS: 2000, BLOB_REVOKE: 10000 };

type ErrorLevel = 'L' | 'M' | 'Q' | 'H';
type ColorMode = 'black' | 'white';

interface QRGeneratorProps {
  translations: Translations;
}

// Simple debounce hook
function useDebounce<T>(value: T, delay: number): T {
  const [debouncedValue, setDebouncedValue] = useState<T>(value);

  useEffect(() => {
    const handler = setTimeout(() => {
      setDebouncedValue(value);
    }, delay);

    return () => {
      clearTimeout(handler);
    };
  }, [value, delay]);

  return debouncedValue;
}

export const QRGenerator = memo(function QRGenerator({ translations: t }: QRGeneratorProps) {
  const [url, setUrl] = useState('');
  const [errorLevel, setErrorLevel] = useState<ErrorLevel>('H');
  const [colorMode, setColorMode] = useState<ColorMode>('black');
  const [qrBlack, setQrBlack] = useState<string | null>(null);
  const [qrWhite, setQrWhite] = useState<string | null>(null);
  const [copySuccess, setCopySuccess] = useState(false);

  const debouncedUrl = useDebounce(url, URL_DEBOUNCE_MS);

  const errorLevels = useMemo(
    () => [
      { level: 'L' as const, recovery: '7%', use: t.onlineOnly, desc: t.noDamageRisk },
      { level: 'M' as const, recovery: '15%', use: t.smallPrint, desc: t.coatedSurface },
      { level: 'Q' as const, recovery: '25%', use: t.generalPrint, desc: t.paperLabel },
      { level: 'H' as const, recovery: '30%', use: t.outdoorLarge, desc: t.highDamageRisk },
    ],
    [t]
  );

  const makeTransparent = useCallback((canvas: HTMLCanvasElement, isWhite: boolean): string => {
    const ctx = canvas.getContext('2d');
    if (!ctx) return '';

    const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
    const data = imageData.data;

    for (let i = 0; i < data.length; i += 4) {
      const r = data[i];
      const g = data[i + 1];
      const b = data[i + 2];

      if (isWhite) {
        if (r <= COLOR_THRESHOLD.BLACK && g <= COLOR_THRESHOLD.BLACK && b <= COLOR_THRESHOLD.BLACK) {
          data[i + 3] = 0;
        } else {
          data[i] = 255;
          data[i + 1] = 255;
          data[i + 2] = 255;
          data[i + 3] = 255;
        }
      } else {
        if (r >= COLOR_THRESHOLD.WHITE && g >= COLOR_THRESHOLD.WHITE && b >= COLOR_THRESHOLD.WHITE) {
          data[i + 3] = 0;
        } else {
          data[i] = 0;
          data[i + 1] = 0;
          data[i + 2] = 0;
          data[i + 3] = 255;
        }
      }
    }

    ctx.putImageData(imageData, 0, 0);
    return canvas.toDataURL('image/png');
  }, []);

  const createQR = useCallback(
    (text: string, level: ErrorLevel) => {
      if (!text.trim()) return;

      const canvas1 = document.createElement('canvas');
      new QRious({
        element: canvas1,
        value: text,
        size: QR_SIZE,
        level: level,
        background: 'white',
        foreground: 'black',
      });

      const blackQR = makeTransparent(canvas1, false);
      setQrBlack(blackQR);

      const canvas2 = document.createElement('canvas');
      new QRious({
        element: canvas2,
        value: text,
        size: QR_SIZE,
        level: level,
        background: 'black',
        foreground: 'white',
      });

      const whiteQR = makeTransparent(canvas2, true);
      setQrWhite(whiteQR);
    },
    [makeTransparent]
  );

  useEffect(() => {
    if (!debouncedUrl.trim()) {
      setQrBlack(null);
      setQrWhite(null);
      return;
    }

    createQR(debouncedUrl, errorLevel);
  }, [debouncedUrl, errorLevel, createQR]);

  const downloadQR = useCallback((dataUrl: string, filename: string) => {
    try {
      const link = document.createElement('a');
      link.href = dataUrl;
      link.download = filename;

      if (navigator.userAgent.match(/iPhone|iPad|iPod/i)) {
        link.target = '_blank';
        link.rel = 'noopener noreferrer';
      }

      document.body.appendChild(link);
      link.click();

      setTimeout(() => {
        document.body.removeChild(link);
      }, TIMEOUTS.DOWNLOAD_CLEANUP);
    } catch (error) {
      console.error('Download error:', error);
      try {
        const newWindow = window.open(dataUrl, '_blank');
        if (!newWindow) {
          alert(t.popupBlocked);
        }
      } catch {
        alert(t.downloadFailed);
      }
    }
  }, [t]);

  const fallbackDownload = useCallback(
    (dataUrl: string) => {
      const link = document.createElement('a');
      link.href = dataUrl;
      link.download = `qr_${colorMode}.png`;
      link.click();
      alert(t.imageCopyNotSupported);
    },
    [colorMode, t]
  );

  const copyImage = useCallback(
    async (dataUrl: string) => {
      try {
        const img = new Image();
        img.crossOrigin = 'anonymous';

        img.onload = async () => {
          try {
            const canvas = document.createElement('canvas');
            canvas.width = img.width;
            canvas.height = img.height;
            const ctx = canvas.getContext('2d');
            if (!ctx) return;
            ctx.drawImage(img, 0, 0);

            canvas.toBlob(
              async (blob) => {
                if (!blob) {
                  throw new Error('Blob creation failed');
                }

                if (navigator.clipboard && typeof ClipboardItem !== 'undefined') {
                  try {
                    const item = new ClipboardItem({ 'image/png': blob });
                    await navigator.clipboard.write([item]);
                    setCopySuccess(true);
                    setTimeout(() => {
                      setCopySuccess(false);
                    }, TIMEOUTS.COPY_SUCCESS);
                    return;
                  } catch (clipErr) {
                    console.log('Clipboard API failed, trying fallback:', clipErr);
                  }
                }

                const blobUrl = URL.createObjectURL(blob);
                const link = document.createElement('a');
                link.href = blobUrl;
                link.download = `qr_${colorMode}.png`;

                if (navigator.userAgent.match(/iPhone|iPad|iPod|Android/i)) {
                  const newWindow = window.open(blobUrl, '_blank');
                  if (newWindow) {
                    alert(t.imageOpenedInNewTab);
                  } else {
                    link.click();
                    alert(t.imageDownloaded);
                  }
                } else {
                  if (confirm(t.imageCopyConfirm)) {
                    link.click();
                  }
                }

                setTimeout(() => URL.revokeObjectURL(blobUrl), TIMEOUTS.BLOB_REVOKE);
              },
              'image/png',
              1.0
            );
          } catch (err) {
            console.error('Canvas processing error:', err);
            fallbackDownload(dataUrl);
          }
        };

        img.onerror = () => {
          console.error('Image load failed');
          fallbackDownload(dataUrl);
        };

        img.src = dataUrl;
      } catch (error) {
        console.error('Copy error:', error);
        fallbackDownload(dataUrl);
      }
    },
    [colorMode, t, fallbackDownload]
  );

  const currentQR = colorMode === 'black' ? qrBlack : qrWhite;
  const currentFilename =
    colorMode === 'black'
      ? 'high_recovery_transparent_qr_black.png'
      : 'high_recovery_transparent_qr_white.png';

  return (
    <div className="qr-generator">
      {/* Input Section */}
      <div className="qr-section">
        <div className="qr-input-group">
          <label className="qr-label">{t.urlLabel}</label>
          <input
            type="text"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            placeholder={t.urlPlaceholder}
            className="qr-input"
          />
          <p className="qr-help">{t.urlHelp}</p>
        </div>
      </div>

      {/* Error Level Section */}
      <div className="qr-section">
        <h3 className="qr-section-title">{t.errorCorrectionLevel}</h3>
        <div className="qr-level-buttons">
          {errorLevels.map((item) => (
            <button
              key={item.level}
              onClick={() => setErrorLevel(item.level)}
              className={`qr-level-btn ${errorLevel === item.level ? 'active' : ''}`}
            >
              <span className="qr-level-letter">{item.level}</span>
              <span className="qr-level-recovery">{item.recovery}</span>
            </button>
          ))}
        </div>
        <p className="qr-help">{t.errorLevelInfo}</p>
      </div>

      {/* Color Section */}
      <div className="qr-section">
        <h3 className="qr-section-title">{t.qrCodeColor}</h3>
        <div className="qr-color-buttons">
          <button
            onClick={() => setColorMode('black')}
            className={`qr-color-btn ${colorMode === 'black' ? 'active' : ''}`}
          >
            {t.black}
          </button>
          <button
            onClick={() => setColorMode('white')}
            className={`qr-color-btn ${colorMode === 'white' ? 'active' : ''}`}
          >
            {t.white}
          </button>
        </div>
      </div>

      {/* QR Preview */}
      <div className="qr-section">
        <h3 className="qr-section-title">{t.generatedQrCode}</h3>
        <div className={`qr-preview ${colorMode === 'black' ? 'light-bg' : 'dark-bg'}`}>
          {currentQR ? (
            <img
              src={currentQR}
              alt={`${colorMode === 'black' ? 'Black' : 'White'} QR Code`}
              className="qr-image"
            />
          ) : (
            <div className={`qr-placeholder ${colorMode === 'black' ? 'light' : 'dark'}`}>
              <svg
                className="qr-placeholder-icon"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M12 4v1m6 11h2m-6 0h-2v4m0-11v3m0 0h.01M12 12h4.01M16 20h4M4 12h4m12 0h.01M5 8h2a1 1 0 001-1V5a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1zm12 0h2a1 1 0 001-1V5a1 1 0 00-1-1h-2a1 1 0 00-1 1v2a1 1 0 001 1zM5 20h2a1 1 0 001-1v-2a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1z"
                />
              </svg>
              <p>{t.enterUrl}</p>
            </div>
          )}
        </div>
        {currentQR && (
          <div className="qr-actions">
            <button onClick={() => copyImage(currentQR)} className="qr-btn qr-btn--secondary">
              <svg width="16" height="16" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <rect x="9" y="9" width="13" height="13" rx="2" strokeWidth="2" />
                <path strokeWidth="2" d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" />
              </svg>
              {copySuccess ? t.copied : t.copyImage}
            </button>
            <button
              onClick={() => downloadQR(currentQR, currentFilename)}
              className="qr-btn qr-btn--primary"
            >
              <svg width="16" height="16" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3"
                />
              </svg>
              {t.download}
            </button>
          </div>
        )}
        <p className="qr-spec">{t.transparentBg}</p>
      </div>

      {/* Footer */}
      <div className="qr-footer">
        <p>{t.footer}</p>
      </div>
    </div>
  );
});

QRGenerator.displayName = 'QRGenerator';

// src/lib/apps/qr/components/QRGenerator.svelte
<script lang="ts">
  import QRious from 'qrious';
  import { t } from '../../../stores';
  import { QR_SIZE, URL_DEBOUNCE_MS, COLOR_THRESHOLD, TIMEOUTS } from '../constants';
  import './QRGenerator.css';

  type ErrorLevel = 'L' | 'M' | 'Q' | 'H';
  type ColorMode = 'black' | 'white';

  let url = '';
  let errorLevel: ErrorLevel = 'H';
  let colorMode: ColorMode = 'black';
  let qrBlack: string | null = null;
  let qrWhite: string | null = null;
  let copySuccess = false;
  let debounceTimer: ReturnType<typeof setTimeout>;

  $: qr = $t.qr;
  $: common = $t.common;

  $: errorLevels = [
    { level: 'L' as const, recovery: '7%', use: qr.onlineOnly, desc: qr.noDamageRisk },
    { level: 'M' as const, recovery: '15%', use: qr.smallPrint, desc: qr.coatedSurface },
    { level: 'Q' as const, recovery: '25%', use: qr.generalPrint, desc: qr.paperLabel },
    { level: 'H' as const, recovery: '30%', use: qr.outdoorLarge, desc: qr.highDamageRisk },
  ];

  function makeTransparent(canvas: HTMLCanvasElement, isWhite: boolean): string {
    const ctx = canvas.getContext('2d');
    if (!ctx) return '';

    const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
    const data = imageData.data;

    for (let i = 0; i < data.length; i += 4) {
      const r = data[i];
      const g = data[i + 1];
      const b = data[i + 2];

      if (isWhite) {
        if (r <= COLOR_THRESHOLD.BLACK && g <= COLOR_THRESHOLD.BLACK && b <= COLOR_THRESHOLD.BLACK) {
          data[i + 3] = 0;
        } else {
          data[i] = 255;
          data[i + 1] = 255;
          data[i + 2] = 255;
          data[i + 3] = 255;
        }
      } else {
        if (r >= COLOR_THRESHOLD.WHITE && g >= COLOR_THRESHOLD.WHITE && b >= COLOR_THRESHOLD.WHITE) {
          data[i + 3] = 0;
        } else {
          data[i] = 0;
          data[i + 1] = 0;
          data[i + 2] = 0;
          data[i + 3] = 255;
        }
      }
    }

    ctx.putImageData(imageData, 0, 0);
    return canvas.toDataURL('image/png');
  }

  function createQR(text: string, level: ErrorLevel) {
    if (!text.trim()) {
      qrBlack = null;
      qrWhite = null;
      return;
    }

    const canvas1 = document.createElement('canvas');
    new QRious({
      element: canvas1,
      value: text,
      size: QR_SIZE,
      level: level,
      background: 'white',
      foreground: 'black',
    });

    qrBlack = makeTransparent(canvas1, false);

    const canvas2 = document.createElement('canvas');
    new QRious({
      element: canvas2,
      value: text,
      size: QR_SIZE,
      level: level,
      background: 'black',
      foreground: 'white',
    });

    qrWhite = makeTransparent(canvas2, true);
  }

  function handleUrlInput() {
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => {
      createQR(url, errorLevel);
    }, URL_DEBOUNCE_MS);
  }

  function handleErrorLevelChange() {
    createQR(url, errorLevel);
  }

  async function handleCopyImage() {
    const qrData = colorMode === 'black' ? qrBlack : qrWhite;
    if (!qrData) return;

    try {
      const response = await fetch(qrData);
      const blob = await response.blob();
      await navigator.clipboard.write([
        new ClipboardItem({ 'image/png': blob }),
      ]);
      copySuccess = true;
      setTimeout(() => copySuccess = false, TIMEOUTS.COPY_SUCCESS);
    } catch {
      alert(qr.imageCopyNotSupported);
    }
  }

  function handleDownload() {
    const qrData = colorMode === 'black' ? qrBlack : qrWhite;
    if (!qrData) return;

    const link = document.createElement('a');
    link.download = `qr-code-${colorMode}.png`;
    link.href = qrData;
    link.click();
  }

  $: currentQR = colorMode === 'black' ? qrBlack : qrWhite;
</script>

<div class="qr-generator">
  <!-- URL Input -->
  <div class="qr-input-section">
    <label class="qr-label" for="url-input">{qr.urlLabel}</label>
    <input
      id="url-input"
      type="url"
      class="qr-url-input"
      placeholder={qr.urlPlaceholder}
      bind:value={url}
      on:input={handleUrlInput}
    />
    <p class="qr-help">{qr.urlHelp}</p>
  </div>

  <!-- Error Correction Level -->
  <div class="qr-error-section">
    <label class="qr-label">{qr.errorCorrectionLevel}</label>
    <div class="error-levels">
      {#each errorLevels as level}
        <label class="error-level-option" class:selected={errorLevel === level.level}>
          <input
            type="radio"
            name="errorLevel"
            value={level.level}
            bind:group={errorLevel}
            on:change={handleErrorLevelChange}
          />
          <span class="error-level-info">
            <strong>{qr.level} {level.level}</strong>
            <span class="error-recovery">({qr.recoveryRate}: {level.recovery})</span>
            <span class="error-use">{level.use}</span>
          </span>
        </label>
      {/each}
    </div>
    <p class="qr-info">{qr.errorLevelInfo}</p>
  </div>

  <!-- Color Mode -->
  <div class="qr-color-section">
    <label class="qr-label">{qr.qrCodeColor}</label>
    <div class="color-modes">
      <button
        class="color-mode-btn"
        class:selected={colorMode === 'black'}
        on:click={() => colorMode = 'black'}
      >
        {qr.black}
      </button>
      <button
        class="color-mode-btn"
        class:selected={colorMode === 'white'}
        on:click={() => colorMode = 'white'}
      >
        {qr.white}
      </button>
    </div>
  </div>

  <!-- QR Code Display -->
  <div class="qr-display-section">
    <label class="qr-label">{qr.generatedQrCode}</label>
    <div class="qr-preview" class:qr-preview-dark={colorMode === 'white'}>
      {#if currentQR}
        <img src={currentQR} alt={colorMode === 'black' ? qr.blackQrCode : qr.whiteQrCode} />
      {:else}
        <p class="qr-placeholder">{qr.enterUrl}</p>
      {/if}
    </div>
    <p class="qr-transparent-note">{qr.transparentBg}</p>
  </div>

  <!-- Actions -->
  {#if currentQR}
    <div class="qr-actions">
      <button class="qr-btn qr-btn-copy" on:click={handleCopyImage}>
        {copySuccess ? common.common.copied : common.common.copyImage}
      </button>
      <button class="qr-btn qr-btn-download" on:click={handleDownload}>
        {common.common.download}
      </button>
    </div>
  {/if}

  <!-- Footer -->
  <p class="qr-footer">{qr.footer}</p>
</div>
