// src/components/navigation/Sidebar.svelte
<script lang="ts">
  import { link, useLocation } from 'svelte-routing';
  import { language } from '../../stores';
  import { MUSIC_APP_PATHS } from '../../constants/apps';
  import type { App } from '../../types';
  import './Sidebar.css';

  export let apps: App[] = [];

  const location = useLocation();

  function isActive(path: string): boolean {
    if (path === '/') return $location.pathname === '/';
    return $location.pathname.startsWith(path);
  }

  $: musicApps = apps.filter(app => (MUSIC_APP_PATHS as readonly string[]).includes(app.url));
  $: otherApps = apps.filter(app => !(MUSIC_APP_PATHS as readonly string[]).includes(app.url));
</script>

<aside class="sidebar">
  <nav class="sidebar-nav">
    <!-- Home -->
    <a href="/" use:link class="sidebar-item" class:active={isActive('/')}>
      <svg class="sidebar-icon" viewBox="0 0 24 24" fill="currentColor">
        {#if isActive('/')}
          <path d="M4 21V10.08l8-6.96 8 6.96V21h-6v-6h-4v6H4z" />
        {:else}
          <path d="M4 21V10.08l8-6.96 8 6.96V21h-6v-6h-4v6H4zm2-2h2v-6h8v6h2V11l-6-5.25L6 11v8z" />
        {/if}
      </svg>
      <span class="sidebar-label">{$language === 'ko' ? '홈' : 'Home'}</span>
    </a>

    <div class="sidebar-divider"></div>

    <!-- Music Section -->
    <div class="sidebar-section-title">
      {$language === 'ko' ? '음악 도구' : 'Music Tools'}
    </div>

    {#each musicApps as app}
      <a href={app.url} use:link class="sidebar-item" class:active={isActive(app.url)}>
        <span class="sidebar-icon sidebar-emoji">{app.icon}</span>
        <span class="sidebar-label">
          {$language === 'ko' ? app.name.ko : app.name.en}
        </span>
      </a>
    {/each}

    <div class="sidebar-divider"></div>

    <!-- Other Tools -->
    <div class="sidebar-section-title">
      {$language === 'ko' ? '기타 도구' : 'Other Tools'}
    </div>

    {#each otherApps as app}
      <a href={app.url} use:link class="sidebar-item" class:active={isActive(app.url)}>
        <span class="sidebar-icon sidebar-emoji">{app.icon}</span>
        <span class="sidebar-label">
          {$language === 'ko' ? app.name.ko : app.name.en}
        </span>
      </a>
    {/each}

    <div class="sidebar-divider"></div>

    <!-- Menu / Settings -->
    <a href="/sitemap" use:link class="sidebar-item" class:active={isActive('/sitemap')}>
      <svg class="sidebar-icon" viewBox="0 0 24 24" fill="currentColor">
        <path d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z" />
      </svg>
      <span class="sidebar-label">{$language === 'ko' ? '메뉴' : 'Menu'}</span>
    </a>
  </nav>
</aside>

// src/components/navigation/Sidebar.tsx
import { memo } from 'react';
import { NavLink, useLocation } from 'react-router-dom';
import { useLanguage } from '../../i18n';
import type { App } from '../../types';
import './Sidebar.css';

interface SidebarProps {
  apps: App[];
}

/**
 * Desktop Sidebar Navigation (YouTube Style)
 * - Fixed on left
 * - Icon + label for each item
 * - Active state highlight
 */
export const Sidebar = memo(function Sidebar({ apps }: SidebarProps) {
  const { language } = useLanguage();
  const location = useLocation();

  const isActive = (path: string) => {
    if (path === '/') return location.pathname === '/';
    return location.pathname.startsWith(path);
  };

  // Get music apps
  const musicApps = apps.filter(app =>
    ['/metronome', '/drum', '/drum-synth'].includes(app.url)
  );

  // Get other apps
  const otherApps = apps.filter(app =>
    !['/metronome', '/drum', '/drum-synth'].includes(app.url)
  );

  return (
    <aside className="sidebar">
      <nav className="sidebar-nav">
        {/* Home */}
        <NavLink to="/" className={`sidebar-item ${isActive('/') ? 'active' : ''}`}>
          <svg className="sidebar-icon" viewBox="0 0 24 24" fill="currentColor">
            {isActive('/') ? (
              <path d="M4 21V10.08l8-6.96 8 6.96V21h-6v-6h-4v6H4z" />
            ) : (
              <path d="M4 21V10.08l8-6.96 8 6.96V21h-6v-6h-4v6H4zm2-2h2v-6h8v6h2V11l-6-5.25L6 11v8z" />
            )}
          </svg>
          <span className="sidebar-label">{language === 'ko' ? '홈' : 'Home'}</span>
        </NavLink>

        <div className="sidebar-divider" />

        {/* Music Section */}
        <div className="sidebar-section-title">
          {language === 'ko' ? '음악 도구' : 'Music Tools'}
        </div>

        {musicApps.map(app => (
          <NavLink
            key={app.url}
            to={app.url}
            className={`sidebar-item ${isActive(app.url) ? 'active' : ''}`}
          >
            <span className="sidebar-icon sidebar-emoji">{app.icon}</span>
            <span className="sidebar-label">
              {language === 'ko' ? app.name.ko : app.name.en}
            </span>
          </NavLink>
        ))}

        <div className="sidebar-divider" />

        {/* Other Tools */}
        <div className="sidebar-section-title">
          {language === 'ko' ? '기타 도구' : 'Other Tools'}
        </div>

        {otherApps.map(app => (
          <NavLink
            key={app.url}
            to={app.url}
            className={`sidebar-item ${isActive(app.url) ? 'active' : ''}`}
          >
            <span className="sidebar-icon sidebar-emoji">{app.icon}</span>
            <span className="sidebar-label">
              {language === 'ko' ? app.name.ko : app.name.en}
            </span>
          </NavLink>
        ))}

        <div className="sidebar-divider" />

        {/* Menu / Settings */}
        <NavLink to="/sitemap" className={`sidebar-item ${isActive('/sitemap') ? 'active' : ''}`}>
          <svg className="sidebar-icon" viewBox="0 0 24 24" fill="currentColor">
            <path d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z" />
          </svg>
          <span className="sidebar-label">{language === 'ko' ? '메뉴' : 'Menu'}</span>
        </NavLink>
      </nav>
    </aside>
  );
});

Sidebar.displayName = 'Sidebar';
