// src/pages/Home.svelte
<script lang="ts">
  import { loadApps } from '../constants/apps';
  import { language, t } from '../stores';
  import AppList from '../components/AppList.svelte';
  import type { App, SortOption } from '../types';
  import { onMount } from 'svelte';

  let apps: App[] = [];
  let isLoading = true;
  let sortBy: SortOption = 'name-asc';
  let isPending = false;

  // Load apps on mount
  onMount(async () => {
    apps = await loadApps();
    isLoading = false;
  });

  // Sort options with translations
  $: homeT = $t.common.home;
  $: sortOptions = [
    { value: 'name-asc' as const, label: homeT.sort.nameAsc },
    { value: 'name-desc' as const, label: homeT.sort.nameDesc },
    { value: 'name-long' as const, label: homeT.sort.nameLong },
    { value: 'name-short' as const, label: homeT.sort.nameShort },
    { value: 'size-large' as const, label: homeT.sort.sizeLarge },
    { value: 'size-small' as const, label: homeT.sort.sizeSmall },
  ];

  // Sort apps
  function sortApps(apps: readonly App[], sortBy: SortOption, lang: 'ko' | 'en'): readonly App[] {
    const sorted = [...apps];
    const locale = lang === 'ko' ? 'ko' : 'en';

    switch (sortBy) {
      case 'name-asc':
        return sorted.sort((a, b) => a.name[lang].localeCompare(b.name[lang], locale));
      case 'name-desc':
        return sorted.sort((a, b) => b.name[lang].localeCompare(a.name[lang], locale));
      case 'name-long':
        return sorted.sort((a, b) => b.name[lang].length - a.name[lang].length);
      case 'name-short':
        return sorted.sort((a, b) => a.name[lang].length - b.name[lang].length);
      case 'size-large':
        return sorted.sort((a, b) => b.size - a.size);
      case 'size-small':
        return sorted.sort((a, b) => a.size - b.size);
      default:
        return apps;
    }
  }

  $: sortedApps = sortApps(apps, sortBy, $language);

  function handleSortChange(e: Event) {
    const target = e.target as HTMLSelectElement;
    isPending = true;
    sortBy = target.value as SortOption;
    // Simulate transition
    setTimeout(() => isPending = false, 100);
  }

  $: appListAriaLabel = $language === 'ko' ? '사용 가능한 도구' : 'Available tools';
</script>

<div class="home-page">
  <!-- Page Header with Controls -->
  <div class="home-header">
    <h1 class="home-title">
      {$language === 'ko' ? '모든 도구' : 'All Tools'}
    </h1>
    <div class="home-controls">
      <!-- Sort Dropdown -->
      <select
        class="sort-dropdown"
        bind:value={sortBy}
        on:change={handleSortChange}
        aria-label={homeT.sortAriaLabel}
      >
        {#each sortOptions as option}
          <option value={option.value}>{option.label}</option>
        {/each}
      </select>
    </div>
  </div>

  <!-- App Grid -->
  <AppList
    apps={sortedApps}
    isPending={isPending || isLoading}
    language={$language}
    ariaLabel={appListAriaLabel}
  />

  <!-- No Results Message -->
  {#if sortedApps.length === 0 && !isLoading}
    <p class="no-results">
      {$language === 'ko' ? '도구가 없습니다.' : 'No tools found.'}
    </p>
  {/if}
</div>

// src/pages/Home.tsx
import { memo, useState, useMemo, useCallback, useTransition } from 'react';
import { useLanguage } from '../i18n';
import { useSEO, useApps } from '../hooks';
import AppList from '../components/AppList';
import type { App, SortOption } from '../types';
import type { Language } from '../i18n/types';

const homeSEO = {
  ko: {
    description:
      '무료 온라인 도구 모음. QR 코드 생성기로 고해상도 QR코드를 만들고, 정밀 메트로놈으로 음악 연습을 하세요. 모든 도구 100% 무료, 회원가입 불필요!',
    keywords:
      'QR코드 생성기, 무료 QR코드, 메트로놈 온라인, 무료 메트로놈, 온라인 도구, 무료 도구, free tools',
  },
  en: {
    description:
      'Free online tools. Create high-resolution QR codes and practice music with precision metronome. All tools 100% free, no signup required!',
    keywords:
      'QR code generator, free QR code, online metronome, free metronome, online tools, free tools',
  },
};

/**
 * Sort apps based on selected option
 * Uses stable sort for consistent ordering
 */
function sortApps(
  apps: readonly App[],
  sortBy: SortOption,
  language: Language
): readonly App[] {
  const sorted = [...apps];
  const locale = language === 'ko' ? 'ko' : 'en';

  switch (sortBy) {
    case 'name-asc':
      return sorted.sort((a, b) =>
        a.name[language].localeCompare(b.name[language], locale)
      );
    case 'name-desc':
      return sorted.sort((a, b) =>
        b.name[language].localeCompare(a.name[language], locale)
      );
    case 'name-long':
      return sorted.sort(
        (a, b) => b.name[language].length - a.name[language].length
      );
    case 'name-short':
      return sorted.sort(
        (a, b) => a.name[language].length - b.name[language].length
      );
    case 'size-large':
      return sorted.sort((a, b) => b.size - a.size);
    case 'size-small':
      return sorted.sort((a, b) => a.size - b.size);
    default:
      return apps;
  }
}

/**
 * Home Page Component
 * Displays a searchable and sortable list of tools
 * Optimized for instant interactions
 */
const Home = memo(function Home() {
  const { language, t } = useLanguage();
  const homeT = t.common.home;

  // Dynamic SEO for Home page
  useSEO({
    description: homeSEO[language].description,
    keywords: homeSEO[language].keywords,
    basePath: '/',
    isHomePage: true,
  });

  // Use shared apps from context (loaded once by AppsProvider)
  const { apps, isLoading } = useApps();

  // Sort state with transition for non-blocking updates
  const [sortBy, setSortBy] = useState<SortOption>('name-asc');
  const [isPending, startTransition] = useTransition();

  // Sort options with translations
  const sortOptions = useMemo(
    () => [
      { value: 'name-asc' as const, label: homeT.sort.nameAsc },
      { value: 'name-desc' as const, label: homeT.sort.nameDesc },
      { value: 'name-long' as const, label: homeT.sort.nameLong },
      { value: 'name-short' as const, label: homeT.sort.nameShort },
      { value: 'size-large' as const, label: homeT.sort.sizeLarge },
      { value: 'size-small' as const, label: homeT.sort.sizeSmall },
    ],
    [homeT.sort]
  );

  // Sort apps - only recompute when inputs change
  const sortedApps = useMemo(() => {
    return sortApps(apps, sortBy, language);
  }, [apps, sortBy, language]);

  // Sort change with transition for smooth UI
  const handleSortChange = useCallback(
    (e: React.ChangeEvent<HTMLSelectElement>) => {
      startTransition(() => {
        setSortBy(e.target.value as SortOption);
      });
    },
    []
  );

  // Aria label for app list
  const appListAriaLabel =
    language === 'ko' ? '사용 가능한 도구' : 'Available tools';

  return (
    <div className="home-page">
      {/* Page Header with Controls */}
      <div className="home-header">
        <h1 className="home-title">
          {language === 'ko' ? '모든 도구' : 'All Tools'}
        </h1>
        <div className="home-controls">
          {/* Sort Dropdown */}
          <select
            className="sort-dropdown"
            value={sortBy}
            onChange={handleSortChange}
            aria-label={homeT.sortAriaLabel}
          >
            {sortOptions.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
        </div>
      </div>

      {/* App Grid */}
      <AppList
        apps={sortedApps}
        isPending={isPending || isLoading}
        language={language}
        ariaLabel={appListAriaLabel}
      />

      {/* No Results Message */}
      {sortedApps.length === 0 && !isLoading && (
        <p className="no-results">
          {language === 'ko' ? '도구가 없습니다.' : 'No tools found.'}
        </p>
      )}
    </div>
  );
});

Home.displayName = 'Home';

export default Home;
