// src/pages/NotFound.svelte
<script lang="ts">
  import { link } from 'svelte-routing';
  import '../styles/not-found.css';
  import '../styles/tool-page.css';
</script>

<main class="container tool-page" role="main">
  <div class="not-found">
    <h1 class="not-found-code">404</h1>
    <h2 class="not-found-title">페이지를 찾을 수 없습니다</h2>
    <p class="not-found-message">
      요청하신 페이지가 존재하지 않거나 이동되었습니다.
    </p>
    <a href="/" use:link class="not-found-link">
      &larr; 홈으로 돌아가기
    </a>
  </div>
</main>

// src/pages/NotFound.tsx
import { memo, useMemo } from 'react';
import { Link } from 'react-router-dom';
import { useViewTransition } from '../hooks/useViewTransition';
import '../styles/not-found.css';
import '../styles/tool-page.css';

/**
 * 404 Not Found Page
 * - View Transitions API for smooth navigation back to home
 */
const NotFound = memo(function NotFound() {
  const { createClickHandler } = useViewTransition();

  // Memoized home click handler using shared View Transition hook
  const handleHomeClick = useMemo(
    () => createClickHandler('/'),
    [createClickHandler]
  );

  return (
    <main className="container tool-page" role="main">
      <div className="not-found">
        <h1 className="not-found-code">404</h1>
        <h2 className="not-found-title">페이지를 찾을 수 없습니다</h2>
        <p className="not-found-message">
          요청하신 페이지가 존재하지 않거나 이동되었습니다.
        </p>
        <Link to="/" className="not-found-link" onClick={handleHomeClick}>
          ← 홈으로 돌아가기
        </Link>
      </div>
    </main>
  );
});

NotFound.displayName = 'NotFound';

export default NotFound;
