// src/standalone/drum/DrumMachine.tsx
import { memo, useState, useCallback, useRef, useEffect } from 'react';
import type { Translations } from './i18n';
import {
  STEPS,
  INSTRUMENTS,
  TEMPO_RANGE,
  VOLUME_RANGE,
  VELOCITY,
  AUDIO,
  PRESETS,
  DEFAULT_VOLUMES,
  MAX_LOOPS,
  createEmptyPattern,
  copyPattern,
  type Instrument,
  type InstrumentVolumes,
  type Pattern,
} from './constants';

interface DrumMachineProps {
  translations: Translations;
}

export const DrumMachine = memo(function DrumMachine({
  translations: t,
}: DrumMachineProps) {
  const [loops, setLoops] = useState<Pattern[]>([createEmptyPattern()]);
  const [currentLoopIndex, setCurrentLoopIndex] = useState(0);
  const [tempo, setTempo] = useState<number>(TEMPO_RANGE.DEFAULT);
  const [volumes, setVolumes] = useState<InstrumentVolumes>({
    ...DEFAULT_VOLUMES,
  });
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentStep, setCurrentStep] = useState(0);
  const [playingLoopIndex, setPlayingLoopIndex] = useState(0);

  const audioContextRef = useRef<AudioContext | null>(null);
  const schedulerRef = useRef<number | null>(null);
  const nextStepTimeRef = useRef<number>(0);
  const currentStepRef = useRef<number>(0);
  const loopsRef = useRef<Pattern[]>(loops);
  const currentPlayingLoopRef = useRef<number>(0);
  const tempoRef = useRef<number>(tempo);
  const volumesRef = useRef<InstrumentVolumes>(volumes);
  const isPlayingRef = useRef<boolean>(false);
  const noiseBufferCacheRef = useRef<Map<string, AudioBuffer>>(new Map());

  const displayLoopIndex = isPlaying ? playingLoopIndex : currentLoopIndex;
  const pattern = loops[displayLoopIndex];

  useEffect(() => {
    loopsRef.current = loops;
  }, [loops]);
  useEffect(() => {
    tempoRef.current = tempo;
  }, [tempo]);
  useEffect(() => {
    volumesRef.current = volumes;
  }, [volumes]);

  const getAudioContext = useCallback(() => {
    if (!audioContextRef.current) {
      audioContextRef.current = new (
        window.AudioContext ||
        (window as unknown as { webkitAudioContext: typeof AudioContext })
          .webkitAudioContext
      )();
    }
    return audioContextRef.current;
  }, []);

  const getNoiseBuffer = useCallback(
    (ctx: AudioContext, duration: number): AudioBuffer => {
      const key = `noise-${duration}`;
      const cached = noiseBufferCacheRef.current.get(key);
      if (cached && cached.sampleRate === ctx.sampleRate) return cached;
      const buffer = ctx.createBuffer(
        1,
        ctx.sampleRate * duration,
        ctx.sampleRate
      );
      const data = buffer.getChannelData(0);
      for (let i = 0; i < buffer.length; i++) data[i] = Math.random() * 2 - 1;
      noiseBufferCacheRef.current.set(key, buffer);
      return buffer;
    },
    []
  );

  const playSound = useCallback(
    (inst: Instrument, time?: number, velocity: number = VELOCITY.DEFAULT) => {
      const ctx = audioContextRef.current;
      if (!ctx || velocity <= 0) return;
      const startTime = time ?? ctx.currentTime;
      const volumeMultiplier =
        (volumesRef.current[inst] / 100) * (velocity / 100);

      switch (inst) {
        case 'kick': {
          const osc = ctx.createOscillator();
          const gain = ctx.createGain();
          osc.connect(gain);
          gain.connect(ctx.destination);
          osc.frequency.setValueAtTime(AUDIO.KICK.FREQUENCY_START, startTime);
          osc.frequency.exponentialRampToValueAtTime(
            AUDIO.KICK.FREQUENCY_END,
            startTime + AUDIO.KICK.DURATION
          );
          gain.gain.setValueAtTime(
            AUDIO.KICK.GAIN * volumeMultiplier,
            startTime
          );
          gain.gain.exponentialRampToValueAtTime(
            0.01,
            startTime + AUDIO.KICK.DURATION
          );
          osc.start(startTime);
          osc.stop(startTime + AUDIO.KICK.DURATION);
          break;
        }
        case 'snare': {
          const buffer = getNoiseBuffer(ctx, AUDIO.SNARE.DURATION);
          const source = ctx.createBufferSource();
          source.buffer = buffer;
          const gain = ctx.createGain();
          source.connect(gain);
          gain.connect(ctx.destination);
          gain.gain.setValueAtTime(
            AUDIO.SNARE.GAIN * volumeMultiplier,
            startTime
          );
          gain.gain.exponentialRampToValueAtTime(
            0.01,
            startTime + AUDIO.SNARE.DURATION
          );
          source.start(startTime);
          break;
        }
        case 'hihat':
        case 'openhat': {
          const isOpen = inst === 'openhat';
          const duration = isOpen
            ? AUDIO.OPENHAT.DURATION
            : AUDIO.HIHAT.DURATION;
          const buffer = getNoiseBuffer(ctx, duration);
          const source = ctx.createBufferSource();
          source.buffer = buffer;
          const gain = ctx.createGain();
          const filter = ctx.createBiquadFilter();
          filter.type = 'highpass';
          filter.frequency.value = isOpen
            ? AUDIO.OPENHAT.FILTER_FREQUENCY
            : AUDIO.HIHAT.FILTER_FREQUENCY;
          source.connect(filter);
          filter.connect(gain);
          gain.connect(ctx.destination);
          gain.gain.setValueAtTime(
            (isOpen ? AUDIO.OPENHAT.GAIN : AUDIO.HIHAT.GAIN) * volumeMultiplier,
            startTime
          );
          gain.gain.exponentialRampToValueAtTime(0.01, startTime + duration);
          source.start(startTime);
          break;
        }
        case 'clap': {
          const buffer = getNoiseBuffer(ctx, AUDIO.CLAP.DURATION);
          const source = ctx.createBufferSource();
          source.buffer = buffer;
          const gain = ctx.createGain();
          source.connect(gain);
          gain.connect(ctx.destination);
          gain.gain.setValueAtTime(
            AUDIO.CLAP.GAIN * volumeMultiplier,
            startTime
          );
          gain.gain.exponentialRampToValueAtTime(
            0.01,
            startTime + AUDIO.CLAP.DURATION
          );
          source.start(startTime);
          break;
        }
      }
    },
    [getNoiseBuffer]
  );

  const scheduleStep = useCallback(
    (stepIndex: number, loopIndex: number, time: number) => {
      const currentPattern = loopsRef.current[loopIndex];
      if (!currentPattern) return;
      INSTRUMENTS.forEach((inst) => {
        const velocity = currentPattern[inst][stepIndex];
        if (velocity > 0) playSound(inst, time, velocity);
      });
    },
    [playSound]
  );

  const scheduler = useCallback(() => {
    const ctx = audioContextRef.current;
    if (!ctx || !isPlayingRef.current) return;
    const scheduleAheadTime = 0.1;
    const stepDuration = 60 / tempoRef.current / 4;

    while (nextStepTimeRef.current < ctx.currentTime + scheduleAheadTime) {
      scheduleStep(
        currentStepRef.current,
        currentPlayingLoopRef.current,
        nextStepTimeRef.current
      );
      const stepToShow = currentStepRef.current;
      const loopToShow = currentPlayingLoopRef.current;
      const timeUntilStep = (nextStepTimeRef.current - ctx.currentTime) * 1000;
      setTimeout(
        () => {
          setCurrentStep(stepToShow);
          setPlayingLoopIndex(loopToShow);
        },
        Math.max(0, timeUntilStep)
      );

      currentStepRef.current = currentStepRef.current + 1;
      if (currentStepRef.current >= STEPS) {
        currentStepRef.current = 0;
        currentPlayingLoopRef.current =
          (currentPlayingLoopRef.current + 1) % loopsRef.current.length;
      }
      nextStepTimeRef.current += stepDuration;
    }
    schedulerRef.current = requestAnimationFrame(scheduler);
  }, [scheduleStep]);

  const play = useCallback(() => {
    const ctx = getAudioContext();
    if (!ctx) return;
    if (!isPlaying) {
      if (ctx.state === 'suspended') ctx.resume();
      setIsPlaying(true);
      isPlayingRef.current = true;
      nextStepTimeRef.current = ctx.currentTime;
      currentStepRef.current = currentStep;
      schedulerRef.current = requestAnimationFrame(scheduler);
    } else {
      setIsPlaying(false);
      isPlayingRef.current = false;
      if (schedulerRef.current) {
        cancelAnimationFrame(schedulerRef.current);
        schedulerRef.current = null;
      }
    }
  }, [isPlaying, currentStep, getAudioContext, scheduler]);

  const stop = useCallback(() => {
    setIsPlaying(false);
    isPlayingRef.current = false;
    setCurrentStep(0);
    currentStepRef.current = 0;
    setPlayingLoopIndex(0);
    currentPlayingLoopRef.current = 0;
    if (schedulerRef.current) {
      cancelAnimationFrame(schedulerRef.current);
      schedulerRef.current = null;
    }
  }, []);

  const clear = useCallback(() => {
    setLoops([createEmptyPattern()]);
    setCurrentLoopIndex(0);
    setPlayingLoopIndex(0);
    currentPlayingLoopRef.current = 0;
  }, []);

  const setStepVelocity = useCallback(
    (inst: Instrument, step: number, velocity: number) => {
      setLoops((prev) => {
        const targetIndex = isPlaying ? playingLoopIndex : currentLoopIndex;
        const newLoops = [...prev];
        const newPattern = { ...newLoops[targetIndex] };
        newPattern[inst] = newPattern[inst].map((val, i) =>
          i === step ? velocity : val
        );
        newLoops[targetIndex] = newPattern;
        return newLoops;
      });
    },
    [currentLoopIndex, isPlaying, playingLoopIndex]
  );

  const toggleStep = useCallback(
    (inst: Instrument, step: number) => {
      const current = pattern[inst][step];
      setStepVelocity(
        inst,
        step,
        current > 0 ? VELOCITY.OFF : VELOCITY.DEFAULT
      );
    },
    [pattern, setStepVelocity]
  );

  const loadPreset = useCallback(
    (presetName: string) => {
      const preset = PRESETS[presetName];
      if (preset) {
        setLoops((prev) => {
          const newLoops = [...prev];
          newLoops[currentLoopIndex] = copyPattern(preset);
          return newLoops;
        });
      }
    },
    [currentLoopIndex]
  );

  const addLoop = useCallback(() => {
    if (loops.length >= MAX_LOOPS) return;
    setLoops((prev) => [...prev, createEmptyPattern()]);
    setCurrentLoopIndex(loops.length);
  }, [loops.length]);

  const removeLoop = useCallback(() => {
    if (loops.length <= 1) return;
    setLoops((prev) => prev.filter((_, i) => i !== currentLoopIndex));
    setCurrentLoopIndex((prev) => (prev > 0 ? prev - 1 : 0));
  }, [loops.length, currentLoopIndex]);

  const copyLoop = useCallback(() => {
    if (loops.length >= MAX_LOOPS) return;
    setLoops((prev) => [...prev, copyPattern(prev[currentLoopIndex])]);
    setCurrentLoopIndex(loops.length);
  }, [loops, currentLoopIndex]);

  useEffect(() => {
    return () => {
      if (schedulerRef.current) cancelAnimationFrame(schedulerRef.current);
      if (audioContextRef.current) audioContextRef.current.close();
    };
  }, []);

  const getInstrumentLabel = (inst: Instrument): string => {
    const labels: Record<Instrument, string> = {
      kick: t.kick,
      snare: t.snare,
      hihat: t.hihat,
      openhat: t.openhat,
      clap: t.clap,
    };
    return labels[inst];
  };

  const getPresetLabel = (preset: string): string => {
    const labels: Record<string, string> = {
      techno: t.presetTechno,
      house: t.presetHouse,
      trap: t.presetTrap,
      breakbeat: t.presetBreakbeat,
      minimal: t.presetMinimal,
    };
    return labels[preset] || preset;
  };

  return (
    <div className="drum-machine">
      {/* Transport */}
      <div className="drum-transport">
        <div className="drum-transport-buttons">
          <button
            className={`drum-btn ${isPlaying ? 'active' : ''}`}
            onClick={play}
          >
            {isPlaying ? t.pause : t.play}
          </button>
          <button className="drum-btn" onClick={stop}>
            {t.stop}
          </button>
          <button className="drum-btn" onClick={clear}>
            {t.clear}
          </button>
        </div>
        <div className="drum-tempo">
          <span className="drum-tempo-label">{t.tempo}</span>
          <input
            type="range"
            className="drum-slider"
            min={TEMPO_RANGE.MIN}
            max={TEMPO_RANGE.MAX}
            value={tempo}
            onChange={(e) => setTempo(parseInt(e.target.value, 10))}
          />
          <span className="drum-tempo-value">{tempo} BPM</span>
        </div>
      </div>

      {/* Loop Controls */}
      <div className="drum-loop-controls">
        <span className="drum-loop-label">{t.loop}</span>
        <div className="drum-loop-buttons">
          {loops.map((_, i) => (
            <button
              key={i}
              className={`drum-loop-btn ${i === currentLoopIndex ? 'selected' : ''} ${isPlaying && i === playingLoopIndex ? 'playing' : ''}`}
              onClick={() => setCurrentLoopIndex(i)}
            >
              {i + 1}
            </button>
          ))}
        </div>
        <div className="drum-loop-actions">
          <button
            className="drum-action-btn"
            onClick={addLoop}
            disabled={loops.length >= MAX_LOOPS}
          >
            +
          </button>
          <button
            className="drum-action-btn"
            onClick={copyLoop}
            disabled={loops.length >= MAX_LOOPS}
          >
            ⎘
          </button>
          <button
            className="drum-action-btn"
            onClick={removeLoop}
            disabled={loops.length <= 1}
          >
            −
          </button>
        </div>
      </div>

      {/* Sequencer Grid */}
      <div className="drum-sequencer">
        {INSTRUMENTS.map((inst) => (
          <div key={inst} className="drum-track">
            <div className="drum-track-info">
              <div className="drum-track-label">{getInstrumentLabel(inst)}</div>
              <div className="drum-track-volume">
                <input
                  type="range"
                  className="drum-volume-slider"
                  min={VOLUME_RANGE.MIN}
                  max={VOLUME_RANGE.MAX}
                  value={volumes[inst]}
                  onChange={(e) =>
                    setVolumes((prev) => ({
                      ...prev,
                      [inst]: parseInt(e.target.value, 10),
                    }))
                  }
                />
              </div>
            </div>
            <div className="drum-track-steps">
              {Array.from({ length: STEPS }).map((_, step) => {
                const velocity = pattern[inst][step];
                const isActive = velocity > 0;
                return (
                  <button
                    key={step}
                    className={`drum-step ${isActive ? 'active' : ''} ${isPlaying && currentStep === step ? 'playing' : ''}`}
                    onClick={() => toggleStep(inst, step)}
                  />
                );
              })}
            </div>
          </div>
        ))}
      </div>

      {/* Presets */}
      <div className="drum-presets">
        <span className="drum-presets-label">{t.presets}</span>
        <div className="drum-presets-buttons">
          {Object.keys(PRESETS).map((preset) => (
            <button
              key={preset}
              className="drum-preset-btn"
              onClick={() => loadPreset(preset)}
            >
              {getPresetLabel(preset)}
            </button>
          ))}
        </div>
      </div>

      {/* Info */}
      <div className="drum-info">{t.synthesisInfo}</div>
    </div>
  );
});

// src/lib/apps/drum/components/DrumMachine.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';
  import { t } from '../../../stores';
  import './DrumMachine.css';

  let isPlaying = false;
  let tempo = 120;
  let currentStep = 0;
  let volume = 80;
  let audioContext: AudioContext | null = null;
  let schedulerInterval: ReturnType<typeof setInterval> | null = null;

  $: drum = $t.drum;

  // 16-step patterns for each instrument
  let patterns: Record<string, boolean[]> = {
    kick: Array(16).fill(false),
    snare: Array(16).fill(false),
    hihat: Array(16).fill(false),
    openhat: Array(16).fill(false),
    clap: Array(16).fill(false),
  };

  const instruments = [
    { id: 'kick', name: () => drum.kick },
    { id: 'snare', name: () => drum.snare },
    { id: 'hihat', name: () => drum.hihat },
    { id: 'openhat', name: () => drum.openhat },
    { id: 'clap', name: () => drum.clap },
  ];

  function initAudio() {
    if (!audioContext) {
      audioContext = new AudioContext();
    }
    return audioContext;
  }

  function playSound(instrument: string) {
    const ctx = initAudio();
    const osc = ctx.createOscillator();
    const gain = ctx.createGain();

    osc.connect(gain);
    gain.connect(ctx.destination);

    // Simple synthesis based on instrument type
    switch (instrument) {
      case 'kick':
        osc.frequency.setValueAtTime(150, ctx.currentTime);
        osc.frequency.exponentialRampToValueAtTime(40, ctx.currentTime + 0.1);
        gain.gain.setValueAtTime(volume / 100, ctx.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.3);
        osc.type = 'sine';
        osc.start(ctx.currentTime);
        osc.stop(ctx.currentTime + 0.3);
        break;
      case 'snare':
        osc.frequency.value = 200;
        gain.gain.setValueAtTime(volume / 100, ctx.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.15);
        osc.type = 'triangle';
        osc.start(ctx.currentTime);
        osc.stop(ctx.currentTime + 0.15);
        break;
      case 'hihat':
        osc.frequency.value = 8000;
        gain.gain.setValueAtTime((volume / 100) * 0.5, ctx.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.05);
        osc.type = 'square';
        osc.start(ctx.currentTime);
        osc.stop(ctx.currentTime + 0.05);
        break;
      case 'openhat':
        osc.frequency.value = 8000;
        gain.gain.setValueAtTime((volume / 100) * 0.5, ctx.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.2);
        osc.type = 'square';
        osc.start(ctx.currentTime);
        osc.stop(ctx.currentTime + 0.2);
        break;
      case 'clap':
        osc.frequency.value = 1000;
        gain.gain.setValueAtTime((volume / 100) * 0.8, ctx.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.1);
        osc.type = 'sawtooth';
        osc.start(ctx.currentTime);
        osc.stop(ctx.currentTime + 0.1);
        break;
    }
  }

  function scheduler() {
    // Play sounds for current step
    for (const [instrument, pattern] of Object.entries(patterns)) {
      if (pattern[currentStep]) {
        playSound(instrument);
      }
    }
    currentStep = (currentStep + 1) % 16;
  }

  function play() {
    initAudio();
    audioContext?.resume();
    currentStep = 0;
    isPlaying = true;
    const intervalMs = (60 / tempo / 4) * 1000; // 16th notes
    schedulerInterval = setInterval(scheduler, intervalMs);
  }

  function stop() {
    if (schedulerInterval) {
      clearInterval(schedulerInterval);
      schedulerInterval = null;
    }
    isPlaying = false;
    currentStep = 0;
  }

  function clear() {
    stop();
    patterns = {
      kick: Array(16).fill(false),
      snare: Array(16).fill(false),
      hihat: Array(16).fill(false),
      openhat: Array(16).fill(false),
      clap: Array(16).fill(false),
    };
  }

  function toggleStep(instrument: string, step: number) {
    patterns[instrument][step] = !patterns[instrument][step];
    patterns = patterns; // Trigger reactivity
  }

  onDestroy(() => {
    stop();
    if (audioContext) {
      audioContext.close();
    }
  });
</script>

<div class="drum-machine">
  <!-- Transport Controls -->
  <div class="drum-transport">
    {#if isPlaying}
      <button class="drum-btn drum-btn-stop" on:click={stop}>
        {drum.stop}
      </button>
    {:else}
      <button class="drum-btn drum-btn-play" on:click={play}>
        {drum.play}
      </button>
    {/if}
    <button class="drum-btn drum-btn-clear" on:click={clear}>
      {drum.clear}
    </button>
  </div>

  <!-- Tempo Control -->
  <div class="drum-tempo">
    <label>{drum.tempo}: {tempo} BPM</label>
    <input
      type="range"
      min="60"
      max="200"
      bind:value={tempo}
      disabled={isPlaying}
      class="drum-slider"
    />
  </div>

  <!-- Volume Control -->
  <div class="drum-volume">
    <label>{drum.volume}: {volume}%</label>
    <input
      type="range"
      min="0"
      max="100"
      bind:value={volume}
      class="drum-slider"
    />
  </div>

  <!-- Pattern Grid -->
  <div class="drum-grid">
    {#each instruments as instrument}
      <div class="drum-row">
        <span class="drum-instrument">{instrument.name()}</span>
        <div class="drum-steps">
          {#each patterns[instrument.id] as active, step}
            <button
              class="drum-step"
              class:active
              class:current={currentStep === step && isPlaying}
              class:beat-marker={step % 4 === 0}
              on:click={() => toggleStep(instrument.id, step)}
            >
              {step + 1}
            </button>
          {/each}
        </div>
      </div>
    {/each}
  </div>

  <!-- Info -->
  <p class="drum-info">{drum.synthesisInfo}</p>
</div>
