// src/lib/apps/drum/DrumMachine.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { t } from '$lib/stores';
  import { cn } from '$lib/utils';
  import {
    STEPS,
    INSTRUMENTS,
    TEMPO_RANGE,
    VOLUME_RANGE,
    VELOCITY,
    AUDIO,
    PRESETS,
    DEFAULT_VOLUMES,
    MAX_LOOPS,
    createEmptyPattern,
    createInitialLoops,
    copyPattern,
    type Instrument,
    type InstrumentVolumes,
    type MultiLoopPattern,
    type Pattern,
  } from './constants';
  import { exportMidi } from './utils/midiExport';
  import { importMidiFile } from './utils/midiImport';

  // State
  let loops = $state<MultiLoopPattern>(createInitialLoops());
  let loopIds = $state<number[]>([1]);
  let nextLoopId = $state(2);
  let currentLoopIndex = $state(0);
  let tempo = $state(TEMPO_RANGE.DEFAULT);
  let volumes = $state<InstrumentVolumes>({ ...DEFAULT_VOLUMES });
  let isPlaying = $state(false);
  let currentStep = $state(0);
  let playingLoopIndex = $state(0);
  let statusMessage = $state<{ text: string; type: 'success' | 'error' | 'info' } | null>(null);
  let dragLoopIndex = $state<number | null>(null);
  let dragOverLoopIndex = $state<number | null>(null);

  // Derived
  const displayLoopIndex = $derived(isPlaying ? playingLoopIndex : currentLoopIndex);
  const pattern = $derived(loops[displayLoopIndex]);

  // Refs
  let audioContext: AudioContext | null = null;
  let schedulerRef: number | null = null;
  let nextStepTimeRef = 0;
  let currentStepRef = 0;
  let currentPlayingLoopRef = 0;
  let isPlayingRef = false;
  let isDraggingRef = false;
  let paintModeRef: boolean | null = null;
  let fileInput: HTMLInputElement;
  let velocityDragRef: {
    inst: Instrument;
    step: number;
    startY: number;
    startVelocity: number;
    hasMoved: boolean;
  } | null = null;

  function getAudioContext() {
    if (!audioContext) {
      const AudioContextClass = window.AudioContext || (window as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
      if (AudioContextClass) {
        audioContext = new AudioContextClass();
      }
    }
    return audioContext;
  }

  function playSound(inst: Instrument, time?: number, velocity: number = VELOCITY.DEFAULT) {
    const ctx = audioContext;
    if (!ctx || velocity <= 0) return;

    const startTime = time ?? ctx.currentTime;
    const volumeMultiplier = (volumes[inst] / 100) * (velocity / 100);

    switch (inst) {
      case 'kick': {
        const osc = ctx.createOscillator();
        const gain = ctx.createGain();
        osc.connect(gain);
        gain.connect(ctx.destination);
        osc.frequency.setValueAtTime(AUDIO.KICK.FREQUENCY_START, startTime);
        osc.frequency.exponentialRampToValueAtTime(AUDIO.KICK.FREQUENCY_END, startTime + AUDIO.KICK.DURATION);
        gain.gain.setValueAtTime(AUDIO.KICK.GAIN * volumeMultiplier, startTime);
        gain.gain.exponentialRampToValueAtTime(0.01, startTime + AUDIO.KICK.DURATION);
        osc.start(startTime);
        osc.stop(startTime + AUDIO.KICK.DURATION);
        break;
      }
      case 'snare': {
        const buffer = ctx.createBuffer(1, ctx.sampleRate * AUDIO.SNARE.DURATION, ctx.sampleRate);
        const data = buffer.getChannelData(0);
        for (let i = 0; i < buffer.length; i++) data[i] = Math.random() * 2 - 1;
        const source = ctx.createBufferSource();
        source.buffer = buffer;
        const gain = ctx.createGain();
        source.connect(gain);
        gain.connect(ctx.destination);
        gain.gain.setValueAtTime(AUDIO.SNARE.GAIN * volumeMultiplier, startTime);
        gain.gain.exponentialRampToValueAtTime(0.01, startTime + AUDIO.SNARE.DURATION);
        source.start(startTime);
        break;
      }
      case 'hihat':
      case 'openhat': {
        const isOpen = inst === 'openhat';
        const duration = isOpen ? AUDIO.OPENHAT.DURATION : AUDIO.HIHAT.DURATION;
        const buffer = ctx.createBuffer(1, ctx.sampleRate * duration, ctx.sampleRate);
        const data = buffer.getChannelData(0);
        for (let i = 0; i < buffer.length; i++) {
          data[i] = (Math.random() * 2 - 1) * Math.exp(-i / (ctx.sampleRate * 0.1));
        }
        const source = ctx.createBufferSource();
        source.buffer = buffer;
        const gain = ctx.createGain();
        const filter = ctx.createBiquadFilter();
        filter.type = 'highpass';
        filter.frequency.value = isOpen ? AUDIO.OPENHAT.FILTER_FREQUENCY : AUDIO.HIHAT.FILTER_FREQUENCY;
        source.connect(filter);
        filter.connect(gain);
        gain.connect(ctx.destination);
        gain.gain.setValueAtTime((isOpen ? AUDIO.OPENHAT.GAIN : AUDIO.HIHAT.GAIN) * volumeMultiplier, startTime);
        gain.gain.exponentialRampToValueAtTime(0.01, startTime + duration);
        source.start(startTime);
        break;
      }
      case 'clap': {
        const buffer = ctx.createBuffer(1, ctx.sampleRate * AUDIO.CLAP.DURATION, ctx.sampleRate);
        const data = buffer.getChannelData(0);
        for (let i = 0; i < buffer.length; i++) data[i] = Math.random() * 2 - 1;
        const source = ctx.createBufferSource();
        source.buffer = buffer;
        const gain = ctx.createGain();
        source.connect(gain);
        gain.connect(ctx.destination);
        gain.gain.setValueAtTime(AUDIO.CLAP.GAIN * volumeMultiplier, startTime);
        gain.gain.exponentialRampToValueAtTime(0.01, startTime + AUDIO.CLAP.DURATION);
        source.start(startTime);
        break;
      }
    }
  }

  function scheduleStep(stepIndex: number, loopIndex: number, time: number) {
    const currentPattern = loops[loopIndex];
    if (!currentPattern) return;
    INSTRUMENTS.forEach((inst) => {
      const velocity = currentPattern[inst][stepIndex];
      if (velocity > 0) playSound(inst, time, velocity);
    });
  }

  function scheduler() {
    const ctx = audioContext;
    if (!ctx || !isPlayingRef) return;

    const scheduleAheadTime = 0.1;
    const stepDuration = 60 / tempo / 4;

    while (nextStepTimeRef < ctx.currentTime + scheduleAheadTime) {
      scheduleStep(currentStepRef, currentPlayingLoopRef, nextStepTimeRef);

      const stepToShow = currentStepRef;
      const loopToShow = currentPlayingLoopRef;
      const timeUntilStep = (nextStepTimeRef - ctx.currentTime) * 1000;
      setTimeout(() => {
        currentStep = stepToShow;
        playingLoopIndex = loopToShow;
      }, Math.max(0, timeUntilStep));

      currentStepRef = currentStepRef + 1;

      if (currentStepRef >= STEPS) {
        currentStepRef = 0;
        currentPlayingLoopRef = (currentPlayingLoopRef + 1) % loops.length;
      }

      nextStepTimeRef += stepDuration;
    }

    schedulerRef = requestAnimationFrame(scheduler);
  }

  function play() {
    const ctx = getAudioContext();
    if (!ctx) return;

    if (!isPlaying) {
      if (ctx.state === 'suspended') ctx.resume();
      isPlaying = true;
      isPlayingRef = true;
      nextStepTimeRef = ctx.currentTime;
      currentStepRef = currentStep;
      schedulerRef = requestAnimationFrame(scheduler);
    } else {
      isPlaying = false;
      isPlayingRef = false;
      if (schedulerRef) {
        cancelAnimationFrame(schedulerRef);
        schedulerRef = null;
      }
    }
  }

  function stop() {
    isPlaying = false;
    isPlayingRef = false;
    currentStep = 0;
    currentStepRef = 0;
    playingLoopIndex = 0;
    currentPlayingLoopRef = 0;
    if (schedulerRef) {
      cancelAnimationFrame(schedulerRef);
      schedulerRef = null;
    }
  }

  function showStatus(text: string, type: 'success' | 'error' | 'info') {
    statusMessage = { text, type };
    setTimeout(() => (statusMessage = null), 3000);
  }

  function clear() {
    if (loops.length > 1) showStatus($t.drum.clearAllLoops, 'info');
    loops = createInitialLoops();
    loopIds = [1];
    nextLoopId = 2;
    currentLoopIndex = 0;
    playingLoopIndex = 0;
    currentPlayingLoopRef = 0;
  }

  function setStepVelocity(inst: Instrument, step: number, velocity: number) {
    const targetIndex = isPlaying ? playingLoopIndex : currentLoopIndex;
    const newLoops = [...loops];
    const newPattern = { ...newLoops[targetIndex] };
    newPattern[inst] = newPattern[inst].map((val, i) => (i === step ? velocity : val));
    newLoops[targetIndex] = newPattern;
    loops = newLoops;
  }

  function handleStepMouseDown(inst: Instrument, step: number, clientY: number) {
    const currentValue = pattern[inst][step];
    if (currentValue > 0) {
      velocityDragRef = { inst, step, startY: clientY, startVelocity: currentValue, hasMoved: false };
      isDraggingRef = false;
      paintModeRef = null;
    } else {
      isDraggingRef = true;
      paintModeRef = true;
      velocityDragRef = null;
      setStepVelocity(inst, step, VELOCITY.DEFAULT);
    }
  }

  function handleStepMouseEnter(inst: Instrument, step: number) {
    if (isDraggingRef && paintModeRef) {
      setStepVelocity(inst, step, VELOCITY.DEFAULT);
    }
  }

  function handleMouseMove(e: MouseEvent) {
    if (!velocityDragRef) return;
    const { inst, step, startY, startVelocity } = velocityDragRef;
    const deltaY = e.clientY - startY;
    if (Math.abs(deltaY) > 3) {
      velocityDragRef.hasMoved = true;
      const velocityChange = Math.round(-deltaY * 1);
      const newVelocity = Math.max(VELOCITY.OFF, Math.min(VELOCITY.MAX, startVelocity + velocityChange));
      setStepVelocity(inst, step, newVelocity);
    }
  }

  function handleDragEnd() {
    if (velocityDragRef && !velocityDragRef.hasMoved) {
      setStepVelocity(velocityDragRef.inst, velocityDragRef.step, VELOCITY.OFF);
    }
    isDraggingRef = false;
    paintModeRef = null;
    velocityDragRef = null;
  }

  function handleTouchMove(e: TouchEvent) {
    const touch = e.touches[0];
    if (velocityDragRef) {
      const { inst, step, startY, startVelocity } = velocityDragRef;
      const deltaY = touch.clientY - startY;
      if (Math.abs(deltaY) > 3) {
        velocityDragRef.hasMoved = true;
        const velocityChange = Math.round(-deltaY * 1);
        const newVelocity = Math.max(VELOCITY.OFF, Math.min(VELOCITY.MAX, startVelocity + velocityChange));
        setStepVelocity(inst, step, newVelocity);
      }
      return;
    }
    if (!isDraggingRef || !paintModeRef) return;
    const element = document.elementFromPoint(touch.clientX, touch.clientY);
    if (element && element.classList.contains('drum-step')) {
      const inst = element.getAttribute('data-instrument') as Instrument;
      const stepAttr = element.getAttribute('data-step');
      const step = stepAttr ? parseInt(stepAttr, 10) : NaN;
      if (inst && !isNaN(step)) setStepVelocity(inst, step, VELOCITY.DEFAULT);
    }
  }

  function loadPreset(presetName: string) {
    const preset = PRESETS[presetName];
    if (preset) {
      const newLoops = [...loops];
      newLoops[currentLoopIndex] = copyPattern(preset);
      loops = newLoops;
      showStatus($t.drum.loadedPreset.replace('{preset}', presetName), 'success');
    }
  }

  function handleExportMidi() {
    exportMidi({ loops, tempo, filename: 'drum-pattern' });
    showStatus($t.drum.exportSuccess, 'success');
  }

  function handleImportClick() {
    fileInput?.click();
  }

  async function handleFileChange(e: Event) {
    const target = e.target as HTMLInputElement;
    const file = target.files?.[0];
    if (!file) return;
    const result = await importMidiFile(file);
    if (result) {
      const newLoops = [...loops];
      newLoops[currentLoopIndex] = result.pattern;
      loops = newLoops;
      tempo = result.tempo;
      showStatus($t.drum.importSuccess, 'success');
    } else {
      showStatus($t.drum.importError, 'error');
    }
    target.value = '';
  }

  function addLoop() {
    if (loops.length >= MAX_LOOPS) {
      showStatus($t.drum.maxLoopsReached, 'error');
      return;
    }
    loops = [...loops, createEmptyPattern()];
    loopIds = [...loopIds, nextLoopId];
    nextLoopId = nextLoopId + 1;
    currentLoopIndex = loops.length - 1;
  }

  function copyCurrentLoop() {
    if (loops.length >= MAX_LOOPS) {
      showStatus($t.drum.maxLoopsReached, 'error');
      return;
    }
    loops = [...loops, copyPattern(loops[currentLoopIndex])];
    loopIds = [...loopIds, nextLoopId];
    nextLoopId = nextLoopId + 1;
    currentLoopIndex = loops.length - 1;
  }

  function removeCurrentLoop() {
    if (loops.length <= 1) return;
    loops = loops.filter((_, i) => i !== currentLoopIndex);
    loopIds = loopIds.filter((_, i) => i !== currentLoopIndex);
    currentLoopIndex = currentLoopIndex > 0 ? currentLoopIndex - 1 : 0;
  }

  function moveLoopLeft() {
    if (currentLoopIndex <= 0) return;
    const newLoops = [...loops];
    [newLoops[currentLoopIndex - 1], newLoops[currentLoopIndex]] = [newLoops[currentLoopIndex], newLoops[currentLoopIndex - 1]];
    loops = newLoops;
    const newIds = [...loopIds];
    [newIds[currentLoopIndex - 1], newIds[currentLoopIndex]] = [newIds[currentLoopIndex], newIds[currentLoopIndex - 1]];
    loopIds = newIds;
    currentLoopIndex = currentLoopIndex - 1;
  }

  function moveLoopRight() {
    if (currentLoopIndex >= loops.length - 1) return;
    const newLoops = [...loops];
    [newLoops[currentLoopIndex], newLoops[currentLoopIndex + 1]] = [newLoops[currentLoopIndex + 1], newLoops[currentLoopIndex]];
    loops = newLoops;
    const newIds = [...loopIds];
    [newIds[currentLoopIndex], newIds[currentLoopIndex + 1]] = [newIds[currentLoopIndex + 1], newIds[currentLoopIndex]];
    loopIds = newIds;
    currentLoopIndex = currentLoopIndex + 1;
  }

  function handleLoopDragStart(index: number) {
    dragLoopIndex = index;
  }

  function handleLoopDragOver(index: number) {
    if (dragLoopIndex !== null && dragLoopIndex !== index) {
      dragOverLoopIndex = index;
    }
  }

  function handleLoopDragEnd() {
    if (dragLoopIndex !== null && dragOverLoopIndex !== null && dragLoopIndex !== dragOverLoopIndex) {
      const newLoops = [...loops];
      const [draggedLoop] = newLoops.splice(dragLoopIndex, 1);
      newLoops.splice(dragOverLoopIndex, 0, draggedLoop);
      loops = newLoops;
      const newIds = [...loopIds];
      const [draggedId] = newIds.splice(dragLoopIndex, 1);
      newIds.splice(dragOverLoopIndex, 0, draggedId);
      loopIds = newIds;
      if (currentLoopIndex === dragLoopIndex) {
        currentLoopIndex = dragOverLoopIndex;
      } else if (dragLoopIndex < currentLoopIndex && dragOverLoopIndex >= currentLoopIndex) {
        currentLoopIndex = currentLoopIndex - 1;
      } else if (dragLoopIndex > currentLoopIndex && dragOverLoopIndex <= currentLoopIndex) {
        currentLoopIndex = currentLoopIndex + 1;
      }
    }
    dragLoopIndex = null;
    dragOverLoopIndex = null;
  }

  function handleLoopDragLeave() {
    dragOverLoopIndex = null;
  }

  function getInstrumentLabel(inst: Instrument): string {
    const labels: Record<Instrument, string> = {
      kick: $t.drum.kick,
      snare: $t.drum.snare,
      hihat: $t.drum.hihat,
      openhat: $t.drum.openhat,
      clap: $t.drum.clap,
    };
    return labels[inst];
  }

  function getPresetLabel(preset: string): string {
    const labels: Record<string, string> = {
      techno: $t.drum.presetTechno,
      house: $t.drum.presetHouse,
      trap: $t.drum.presetTrap,
      breakbeat: $t.drum.presetBreakbeat,
      minimal: $t.drum.presetMinimal,
    };
    return labels[preset] || preset;
  }

  onMount(() => {
    const handleGlobalMouseUp = () => {
      if (velocityDragRef && !velocityDragRef.hasMoved) {
        setStepVelocity(velocityDragRef.inst, velocityDragRef.step, VELOCITY.OFF);
      }
      isDraggingRef = false;
      paintModeRef = null;
      velocityDragRef = null;
    };
    const handleGlobalMouseMove = (e: MouseEvent) => {
      if (velocityDragRef) handleMouseMove(e);
    };
    window.addEventListener('mouseup', handleGlobalMouseUp);
    window.addEventListener('touchend', handleGlobalMouseUp);
    window.addEventListener('mousemove', handleGlobalMouseMove);
    return () => {
      window.removeEventListener('mouseup', handleGlobalMouseUp);
      window.removeEventListener('touchend', handleGlobalMouseUp);
      window.removeEventListener('mousemove', handleGlobalMouseMove);
    };
  });

  onDestroy(() => {
    if (schedulerRef) cancelAnimationFrame(schedulerRef);
    if (audioContext) audioContext.close();
  });
</script>

<div class="drum-machine">
  <!-- Transport Controls -->
  <div class="drum-transport">
    <div class="drum-transport-controls">
      <button class={cn('drum-btn', isPlaying && 'drum-btn--active')} onclick={play} aria-label={isPlaying ? $t.drum.pause : $t.drum.play}>
        {#if isPlaying}
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="6" y="4" width="4" height="16" /><rect x="14" y="4" width="4" height="16" /></svg>
        {:else}
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3" /></svg>
        {/if}
        <span>{isPlaying ? $t.drum.pause : $t.drum.play}</span>
      </button>
      <button class="drum-btn" onclick={stop} aria-label={$t.drum.stop}>
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2" /></svg>
        <span>{$t.drum.stop}</span>
      </button>
      <button class="drum-btn" onclick={clear} aria-label={$t.drum.clear}>
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 4H8l-7 8 7 8h13a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2z" /><line x1="18" y1="9" x2="12" y2="15" /><line x1="12" y1="9" x2="18" y2="15" /></svg>
        <span>{$t.drum.clear}</span>
      </button>
      <button class="drum-btn drum-btn--export" onclick={handleExportMidi} aria-label={$t.drum.exportMidi}>
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><polyline points="7 10 12 15 17 10" /><line x1="12" y1="15" x2="12" y2="3" /></svg>
        <span>{$t.drum.exportMidi}</span>
      </button>
      <button class="drum-btn drum-btn--import" onclick={handleImportClick} aria-label={$t.drum.importMidi}>
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><polyline points="17 8 12 3 7 8" /><line x1="12" y1="3" x2="12" y2="15" /></svg>
        <span>{$t.drum.importMidi}</span>
      </button>
      <input bind:this={fileInput} type="file" accept=".mid,.midi,audio/midi,audio/x-midi" onchange={handleFileChange} style="display: none" aria-hidden="true" />
    </div>

    <div class="drum-tempo">
      <span class="drum-tempo-label">{$t.drum.tempo}</span>
      <input type="range" class="drum-slider" min={TEMPO_RANGE.MIN} max={TEMPO_RANGE.MAX} bind:value={tempo} aria-label={$t.drum.tempo} />
      <span class="drum-tempo-value">
        {tempo} BPM
        <span class="drum-tempo-duration">
          {loops.length > 1 ? `x${loops.length} ` : ''}({((240 / tempo) * loops.length).toFixed(1)}s)
        </span>
      </span>
    </div>
  </div>

  <!-- Loop Controls -->
  <div class="drum-loop-controls">
    <div class="drum-loop-row">
      <span class="drum-loop-label">{$t.drum.loop}</span>
      <div class="drum-loop-blocks">
        {#each loops as _, index}
          <button
            class={cn(
              'drum-loop-block',
              index === currentLoopIndex && 'drum-loop-block--selected',
              isPlaying && index === playingLoopIndex && 'drum-loop-block--playing',
              dragLoopIndex === index && 'drum-loop-block--dragging',
              dragOverLoopIndex === index && 'drum-loop-block--drag-over'
            )}
            draggable="true"
            ondragstart={() => handleLoopDragStart(index)}
            ondragover={(e) => { e.preventDefault(); handleLoopDragOver(index); }}
            ondragleave={handleLoopDragLeave}
            ondragend={handleLoopDragEnd}
            ondrop={handleLoopDragEnd}
            onclick={() => (currentLoopIndex = index)}
            aria-label={`${$t.drum.loop} ${loopIds[index]}`}
            title={`${$t.drum.loop} ${loopIds[index]}`}
          >
            {loopIds[index]}
          </button>
        {/each}
      </div>
    </div>
    <div class="drum-loop-actions">
      <button class="drum-loop-btn drum-loop-btn--action" onclick={moveLoopLeft} disabled={currentLoopIndex <= 0} aria-label={$t.drum.moveLoopLeft} title={$t.drum.moveLoopLeft}>
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="15 18 9 12 15 6" /></svg>
      </button>
      <button class="drum-loop-btn drum-loop-btn--action" onclick={moveLoopRight} disabled={currentLoopIndex >= loops.length - 1} aria-label={$t.drum.moveLoopRight} title={$t.drum.moveLoopRight}>
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6" /></svg>
      </button>
      <button class="drum-loop-btn drum-loop-btn--action" onclick={addLoop} disabled={loops.length >= MAX_LOOPS} aria-label={$t.drum.addLoop} title={$t.drum.addLoop}>
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19" /><line x1="5" y1="12" x2="19" y2="12" /></svg>
      </button>
      <button class="drum-loop-btn drum-loop-btn--action" onclick={copyCurrentLoop} disabled={loops.length >= MAX_LOOPS} aria-label={$t.drum.copyLoop} title={$t.drum.copyLoop}>
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2" /><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" /></svg>
      </button>
      <button class="drum-loop-btn drum-loop-btn--action" onclick={removeCurrentLoop} disabled={loops.length <= 1} aria-label={$t.drum.removeLoop} title={$t.drum.removeLoop}>
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="12" x2="19" y2="12" /></svg>
      </button>
    </div>
  </div>

  <!-- Sequencer Grid -->
  <div class="drum-sequencer" onmouseup={handleDragEnd} onmouseleave={handleDragEnd} ontouchmove={handleTouchMove} ontouchend={handleDragEnd}>
    {#each INSTRUMENTS as inst}
      <div class="drum-track">
        <div class="drum-track-info">
          <div class="drum-track-label">{getInstrumentLabel(inst)}</div>
          <div class="drum-track-volume">
            <input type="range" class="drum-volume-slider" min={VOLUME_RANGE.MIN} max={VOLUME_RANGE.MAX} bind:value={volumes[inst]} aria-label={`${getInstrumentLabel(inst)} ${$t.drum.volume}`} />
            <span class="drum-volume-value">{volumes[inst]}</span>
          </div>
        </div>
        <div class="drum-track-steps">
          {#each Array(STEPS) as _, step}
            {@const velocity = pattern[inst][step]}
            {@const isActive = velocity > 0}
            {@const opacity = isActive ? 0.3 + (velocity / VELOCITY.MAX) * 0.7 : 1}
            <button
              class={cn('drum-step', isActive && 'drum-step--active', isPlaying && currentStep === step && 'drum-step--playing')}
              style={isActive ? `opacity: ${opacity}` : undefined}
              data-instrument={inst}
              data-step={step}
              onmousedown={(e) => { e.preventDefault(); handleStepMouseDown(inst, step, e.clientY); }}
              onmouseenter={() => handleStepMouseEnter(inst, step)}
              ontouchstart={(e) => { e.preventDefault(); const touch = e.touches[0]; handleStepMouseDown(inst, step, touch.clientY); }}
              aria-label={`${getInstrumentLabel(inst)} ${$t.drum.step} ${step + 1}${isActive ? ` (${velocity}%)` : ''}`}
              aria-pressed={isActive}
            ></button>
          {/each}
        </div>
      </div>
    {/each}
  </div>

  <!-- Presets -->
  <div class="drum-presets">
    <span class="drum-presets-label">{$t.drum.presets}</span>
    <div class="drum-presets-buttons">
      {#each Object.keys(PRESETS) as preset}
        <button class="drum-preset-btn" onclick={() => loadPreset(preset)}>{getPresetLabel(preset)}</button>
      {/each}
    </div>
  </div>

  <!-- Synthesis Info -->
  <div class="drum-synthesis-info">{$t.drum.synthesisInfo}</div>

  <!-- Status Message -->
  {#if statusMessage}
    <div class={cn('drum-status', `drum-status--${statusMessage.type}`)}>{statusMessage.text}</div>
  {/if}
</div>

// src/apps/drum/components/DrumMachine.tsx
import { memo, useState, useCallback, useRef, useEffect } from 'react';
import { useTranslations } from '../../../i18n';
import { cn } from '../../../utils';
import {
  STEPS,
  INSTRUMENTS,
  TEMPO_RANGE,
  VOLUME_RANGE,
  VELOCITY,
  AUDIO,
  PRESETS,
  DEFAULT_VOLUMES,
  createEmptyPattern,
  type Instrument,
  type Pattern,
  type InstrumentVolumes,
} from '../constants';
import { exportMidi } from '../utils/midiExport';
import { importMidiFile } from '../utils/midiImport';
import './DrumMachine.css';

/**
 * Play icon SVG
 */
const PlayIcon = memo(function PlayIcon() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <polygon points="5 3 19 12 5 21 5 3" />
    </svg>
  );
});

/**
 * Pause icon SVG
 */
const PauseIcon = memo(function PauseIcon() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <rect x="6" y="4" width="4" height="16" />
      <rect x="14" y="4" width="4" height="16" />
    </svg>
  );
});

/**
 * Stop icon SVG
 */
const StopIcon = memo(function StopIcon() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
    </svg>
  );
});

/**
 * Clear icon SVG
 */
const ClearIcon = memo(function ClearIcon() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M21 4H8l-7 8 7 8h13a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2z" />
      <line x1="18" y1="9" x2="12" y2="15" />
      <line x1="12" y1="9" x2="18" y2="15" />
    </svg>
  );
});

/**
 * Download/Export icon SVG
 */
const DownloadIcon = memo(function DownloadIcon() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" y1="15" x2="12" y2="3" />
    </svg>
  );
});

/**
 * Upload/Import icon SVG
 */
const UploadIcon = memo(function UploadIcon() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" y1="3" x2="12" y2="15" />
    </svg>
  );
});

/**
 * DrumMachine Component
 * A 16-step drum sequencer with Web Audio synthesis
 */
export const DrumMachine = memo(function DrumMachine() {
  const { drum } = useTranslations();

  // State
  const [pattern, setPattern] = useState<Pattern>(createEmptyPattern);
  const [tempo, setTempo] = useState<number>(TEMPO_RANGE.DEFAULT);
  const [volumes, setVolumes] = useState<InstrumentVolumes>({ ...DEFAULT_VOLUMES });
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentStep, setCurrentStep] = useState(0);
  const [statusMessage, setStatusMessage] = useState<{
    text: string;
    type: 'success' | 'error' | 'info';
  } | null>(null);

  // Refs
  const audioContextRef = useRef<AudioContext | null>(null);
  const schedulerRef = useRef<number | null>(null);
  const nextStepTimeRef = useRef<number>(0);
  const currentStepRef = useRef<number>(0);
  const patternRef = useRef<Pattern>(pattern);
  const tempoRef = useRef<number>(tempo);
  const volumesRef = useRef<InstrumentVolumes>(volumes);
  const isPlayingRef = useRef<boolean>(false);
  const isDraggingRef = useRef(false);
  const paintModeRef = useRef<boolean | null>(null); // true = paint on, false = paint off
  const fileInputRef = useRef<HTMLInputElement | null>(null);
  // Velocity drag refs
  const velocityDragRef = useRef<{
    inst: Instrument;
    step: number;
    startY: number;
    startVelocity: number;
    hasMoved: boolean; // Track if user actually dragged
  } | null>(null);

  // Keep refs in sync with state
  useEffect(() => {
    patternRef.current = pattern;
  }, [pattern]);

  useEffect(() => {
    tempoRef.current = tempo;
  }, [tempo]);

  useEffect(() => {
    volumesRef.current = volumes;
  }, [volumes]);

  /**
   * Get or create audio context
   */
  const getAudioContext = useCallback(() => {
    if (!audioContextRef.current) {
      audioContextRef.current = new (window.AudioContext ||
        (window as unknown as { webkitAudioContext: typeof AudioContext })
          .webkitAudioContext)();
    }
    return audioContextRef.current;
  }, []);

  /**
   * Play a single instrument sound at a specific time
   * @param inst - Instrument to play
   * @param time - Audio context time to schedule the sound
   * @param velocity - Note velocity (0-100), affects volume
   */
  const playSound = useCallback(
    (inst: Instrument, time?: number, velocity: number = VELOCITY.DEFAULT) => {
      const ctx = audioContextRef.current;
      if (!ctx || velocity <= 0) return;

      const startTime = time ?? ctx.currentTime;
      // Combine instrument volume and note velocity
      const volumeMultiplier = (volumesRef.current[inst] / 100) * (velocity / 100);

      switch (inst) {
        case 'kick': {
          const osc = ctx.createOscillator();
          const gain = ctx.createGain();
          osc.connect(gain);
          gain.connect(ctx.destination);
          osc.frequency.setValueAtTime(AUDIO.KICK.FREQUENCY_START, startTime);
          osc.frequency.exponentialRampToValueAtTime(
            AUDIO.KICK.FREQUENCY_END,
            startTime + AUDIO.KICK.DURATION
          );
          gain.gain.setValueAtTime(AUDIO.KICK.GAIN * volumeMultiplier, startTime);
          gain.gain.exponentialRampToValueAtTime(
            0.01,
            startTime + AUDIO.KICK.DURATION
          );
          osc.start(startTime);
          osc.stop(startTime + AUDIO.KICK.DURATION);
          break;
        }
        case 'snare': {
          const buffer = ctx.createBuffer(
            1,
            ctx.sampleRate * AUDIO.SNARE.DURATION,
            ctx.sampleRate
          );
          const data = buffer.getChannelData(0);
          for (let i = 0; i < buffer.length; i++) {
            data[i] = Math.random() * 2 - 1;
          }
          const source = ctx.createBufferSource();
          source.buffer = buffer;
          const gain = ctx.createGain();
          source.connect(gain);
          gain.connect(ctx.destination);
          gain.gain.setValueAtTime(AUDIO.SNARE.GAIN * volumeMultiplier, startTime);
          gain.gain.exponentialRampToValueAtTime(
            0.01,
            startTime + AUDIO.SNARE.DURATION
          );
          source.start(startTime);
          break;
        }
        case 'hihat':
        case 'openhat': {
          const isOpen = inst === 'openhat';
          const duration = isOpen
            ? AUDIO.OPENHAT.DURATION
            : AUDIO.HIHAT.DURATION;
          const buffer = ctx.createBuffer(1, ctx.sampleRate * duration, ctx.sampleRate);
          const data = buffer.getChannelData(0);
          for (let i = 0; i < buffer.length; i++) {
            data[i] =
              (Math.random() * 2 - 1) * Math.exp(-i / (ctx.sampleRate * 0.1));
          }
          const source = ctx.createBufferSource();
          source.buffer = buffer;
          const gain = ctx.createGain();
          const filter = ctx.createBiquadFilter();
          filter.type = 'highpass';
          filter.frequency.value = isOpen
            ? AUDIO.OPENHAT.FILTER_FREQUENCY
            : AUDIO.HIHAT.FILTER_FREQUENCY;
          source.connect(filter);
          filter.connect(gain);
          gain.connect(ctx.destination);
          gain.gain.setValueAtTime(
            (isOpen ? AUDIO.OPENHAT.GAIN : AUDIO.HIHAT.GAIN) * volumeMultiplier,
            startTime
          );
          gain.gain.exponentialRampToValueAtTime(0.01, startTime + duration);
          source.start(startTime);
          break;
        }
        case 'clap': {
          const buffer = ctx.createBuffer(
            1,
            ctx.sampleRate * AUDIO.CLAP.DURATION,
            ctx.sampleRate
          );
          const data = buffer.getChannelData(0);
          for (let i = 0; i < buffer.length; i++) {
            data[i] = Math.random() * 2 - 1;
          }
          const source = ctx.createBufferSource();
          source.buffer = buffer;
          const gain = ctx.createGain();
          source.connect(gain);
          gain.connect(ctx.destination);
          gain.gain.setValueAtTime(AUDIO.CLAP.GAIN * volumeMultiplier, startTime);
          gain.gain.exponentialRampToValueAtTime(
            0.01,
            startTime + AUDIO.CLAP.DURATION
          );
          source.start(startTime);
          break;
        }
      }
    },
    []
  );

  /**
   * Schedule sounds for upcoming steps using Web Audio timing
   */
  const scheduleStep = useCallback(
    (stepIndex: number, time: number) => {
      const currentPattern = patternRef.current;
      INSTRUMENTS.forEach((inst) => {
        const velocity = currentPattern[inst][stepIndex];
        if (velocity > 0) {
          playSound(inst, time, velocity);
        }
      });
    },
    [playSound]
  );

  /**
   * Scheduler loop using requestAnimationFrame
   * Schedules notes ahead of time for accurate timing
   */
  const scheduler = useCallback(() => {
    const ctx = audioContextRef.current;
    if (!ctx || !isPlayingRef.current) return;

    const scheduleAheadTime = 0.1; // Schedule 100ms ahead
    const stepDuration = 60 / tempoRef.current / 4; // Duration of one 16th note in seconds

    // Schedule all notes that fall within the look-ahead window
    while (nextStepTimeRef.current < ctx.currentTime + scheduleAheadTime) {
      scheduleStep(currentStepRef.current, nextStepTimeRef.current);

      // Update visual step (use setTimeout for UI sync)
      const stepToShow = currentStepRef.current;
      const timeUntilStep = (nextStepTimeRef.current - ctx.currentTime) * 1000;
      setTimeout(() => {
        setCurrentStep(stepToShow);
      }, Math.max(0, timeUntilStep));

      // Advance to next step
      currentStepRef.current = (currentStepRef.current + 1) % STEPS;
      nextStepTimeRef.current += stepDuration;
    }

    // Continue scheduling if still playing
    schedulerRef.current = requestAnimationFrame(scheduler);
  }, [scheduleStep]);

  /**
   * Start playback
   */
  const play = useCallback(() => {
    const ctx = getAudioContext();
    if (!ctx) return;

    if (!isPlaying) {
      // Resume audio context if suspended (browser autoplay policy)
      if (ctx.state === 'suspended') {
        ctx.resume();
      }
      setIsPlaying(true);
      isPlayingRef.current = true;
      // Initialize timing from current audio context time
      nextStepTimeRef.current = ctx.currentTime;
      currentStepRef.current = currentStep;
      // Start the scheduler
      schedulerRef.current = requestAnimationFrame(scheduler);
    } else {
      // Pause
      setIsPlaying(false);
      isPlayingRef.current = false;
      if (schedulerRef.current) {
        cancelAnimationFrame(schedulerRef.current);
        schedulerRef.current = null;
      }
    }
  }, [isPlaying, currentStep, getAudioContext, scheduler]);

  /**
   * Stop playback
   */
  const stop = useCallback(() => {
    setIsPlaying(false);
    isPlayingRef.current = false;
    setCurrentStep(0);
    currentStepRef.current = 0;
    if (schedulerRef.current) {
      cancelAnimationFrame(schedulerRef.current);
      schedulerRef.current = null;
    }
  }, []);

  /**
   * Clear pattern
   */
  const clear = useCallback(() => {
    setPattern(createEmptyPattern());
  }, []);

  /**
   * Set a step velocity value
   */
  const setStepVelocity = useCallback((inst: Instrument, step: number, velocity: number) => {
    setPattern((prev) => ({
      ...prev,
      [inst]: prev[inst].map((val, i) => (i === step ? velocity : val)),
    }));
  }, []);

  /**
   * Handle drag start on a step
   */
  const handleStepMouseDown = useCallback(
    (inst: Instrument, step: number, clientY: number) => {
      const currentValue = pattern[inst][step];

      if (currentValue > 0) {
        // Active note: start velocity drag mode (or remove on click without drag)
        velocityDragRef.current = {
          inst,
          step,
          startY: clientY,
          startVelocity: currentValue,
          hasMoved: false,
        };
        isDraggingRef.current = false;
        paintModeRef.current = null;
      } else {
        // Inactive note: start paint mode with full velocity
        isDraggingRef.current = true;
        paintModeRef.current = true;
        velocityDragRef.current = null;
        setStepVelocity(inst, step, VELOCITY.DEFAULT);
      }
    },
    [pattern, setStepVelocity]
  );

  /**
   * Handle mouse enter while dragging (paint mode only)
   */
  const handleStepMouseEnter = useCallback(
    (inst: Instrument, step: number) => {
      if (isDraggingRef.current && paintModeRef.current) {
        setStepVelocity(inst, step, VELOCITY.DEFAULT);
      }
    },
    [setStepVelocity]
  );

  /**
   * Handle mouse move for velocity adjustment
   */
  const handleMouseMove = useCallback(
    (e: React.MouseEvent | MouseEvent) => {
      if (!velocityDragRef.current) return;

      const { inst, step, startY, startVelocity } = velocityDragRef.current;
      // Drag down = decrease velocity, drag up = increase velocity
      const deltaY = e.clientY - startY;

      // Only process if moved more than 3px (threshold to distinguish click from drag)
      if (Math.abs(deltaY) > 3) {
        velocityDragRef.current.hasMoved = true;
        // 100px drag = full velocity change
        const velocityChange = Math.round(-deltaY * 1);
        const newVelocity = Math.max(
          VELOCITY.OFF,
          Math.min(VELOCITY.MAX, startVelocity + velocityChange)
        );
        setStepVelocity(inst, step, newVelocity);
      }
    },
    [setStepVelocity]
  );

  /**
   * Handle drag end - remove note if clicked without dragging
   */
  const handleDragEnd = useCallback(() => {
    // If velocity drag mode was active and user didn't move, remove the note
    if (velocityDragRef.current && !velocityDragRef.current.hasMoved) {
      const { inst, step } = velocityDragRef.current;
      setStepVelocity(inst, step, VELOCITY.OFF);
    }
    isDraggingRef.current = false;
    paintModeRef.current = null;
    velocityDragRef.current = null;
  }, [setStepVelocity]);

  /**
   * Handle touch move for mobile (paint mode and velocity adjustment)
   */
  const handleTouchMove = useCallback(
    (e: React.TouchEvent) => {
      const touch = e.touches[0];

      // Velocity drag mode
      if (velocityDragRef.current) {
        const { inst, step, startY, startVelocity } = velocityDragRef.current;
        const deltaY = touch.clientY - startY;

        // Only process if moved more than 3px
        if (Math.abs(deltaY) > 3) {
          velocityDragRef.current.hasMoved = true;
          const velocityChange = Math.round(-deltaY * 1);
          const newVelocity = Math.max(
            VELOCITY.OFF,
            Math.min(VELOCITY.MAX, startVelocity + velocityChange)
          );
          setStepVelocity(inst, step, newVelocity);
        }
        return;
      }

      // Paint mode
      if (!isDraggingRef.current || !paintModeRef.current) return;

      const element = document.elementFromPoint(touch.clientX, touch.clientY);

      if (element && element.classList.contains('drum-step')) {
        const inst = element.getAttribute('data-instrument') as Instrument;
        const stepAttr = element.getAttribute('data-step');
        const step = stepAttr ? parseInt(stepAttr, 10) : NaN;

        if (inst && !isNaN(step)) {
          setStepVelocity(inst, step, VELOCITY.DEFAULT);
        }
      }
    },
    [setStepVelocity]
  );

  /**
   * Add global mouse listeners for drag handling
   */
  useEffect(() => {
    const handleGlobalMouseUp = () => {
      // If velocity drag mode was active and user didn't move, remove the note
      if (velocityDragRef.current && !velocityDragRef.current.hasMoved) {
        const { inst, step } = velocityDragRef.current;
        setStepVelocity(inst, step, VELOCITY.OFF);
      }
      isDraggingRef.current = false;
      paintModeRef.current = null;
      velocityDragRef.current = null;
    };

    const handleGlobalMouseMove = (e: MouseEvent) => {
      if (velocityDragRef.current) {
        handleMouseMove(e);
      }
    };

    window.addEventListener('mouseup', handleGlobalMouseUp);
    window.addEventListener('touchend', handleGlobalMouseUp);
    window.addEventListener('mousemove', handleGlobalMouseMove);

    return () => {
      window.removeEventListener('mouseup', handleGlobalMouseUp);
      window.removeEventListener('touchend', handleGlobalMouseUp);
      window.removeEventListener('mousemove', handleGlobalMouseMove);
    };
  }, [handleMouseMove, setStepVelocity]);

  /**
   * Show status message
   */
  const showStatus = useCallback(
    (text: string, type: 'success' | 'error' | 'info') => {
      setStatusMessage({ text, type });
      setTimeout(() => setStatusMessage(null), 3000);
    },
    []
  );

  /**
   * Load a preset
   */
  const loadPreset = useCallback(
    (presetName: string) => {
      const preset = PRESETS[presetName];
      if (preset) {
        setPattern({
          kick: [...preset.kick],
          snare: [...preset.snare],
          hihat: [...preset.hihat],
          openhat: [...preset.openhat],
          clap: [...preset.clap],
        });
        showStatus(drum.loadedPreset.replace('{preset}', presetName), 'success');
      }
    },
    [drum.loadedPreset, showStatus]
  );

  /**
   * Export pattern as MIDI file
   */
  const handleExportMidi = useCallback(() => {
    exportMidi({
      pattern,
      tempo,
      filename: 'drum-pattern',
    });
    showStatus(drum.exportSuccess, 'success');
  }, [pattern, tempo, drum.exportSuccess, showStatus]);

  /**
   * Trigger file input for MIDI import
   */
  const handleImportClick = useCallback(() => {
    fileInputRef.current?.click();
  }, []);

  /**
   * Handle MIDI file import
   */
  const handleFileChange = useCallback(
    async (e: React.ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0];
      if (!file) return;

      const result = await importMidiFile(file);

      if (result) {
        setPattern(result.pattern);
        setTempo(result.tempo);
        showStatus(drum.importSuccess, 'success');
      } else {
        showStatus(drum.importError, 'error');
      }

      // Reset input so same file can be selected again
      e.target.value = '';
    },
    [drum.importSuccess, drum.importError, showStatus]
  );

  /**
   * Handle tempo change
   */
  const handleTempoChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const newTempo = parseInt(e.target.value, 10);
      setTempo(newTempo);
      // Scheduler will pick up new tempo automatically on next iteration
    },
    []
  );

  /**
   * Handle instrument volume change
   */
  const handleVolumeChange = useCallback(
    (inst: Instrument, value: number) => {
      setVolumes((prev) => ({ ...prev, [inst]: value }));
    },
    []
  );

  /**
   * Cleanup on unmount
   */
  useEffect(() => {
    return () => {
      if (schedulerRef.current) {
        cancelAnimationFrame(schedulerRef.current);
      }
      if (audioContextRef.current) {
        audioContextRef.current.close();
      }
    };
  }, []);

  /**
   * Get translated instrument label
   */
  const getInstrumentLabel = useCallback(
    (inst: Instrument): string => {
      const labels: Record<Instrument, string> = {
        kick: drum.kick,
        snare: drum.snare,
        hihat: drum.hihat,
        openhat: drum.openhat,
        clap: drum.clap,
      };
      return labels[inst];
    },
    [drum]
  );

  /**
   * Get translated preset label
   */
  const getPresetLabel = useCallback(
    (preset: string): string => {
      const labels: Record<string, string> = {
        techno: drum.presetTechno,
        house: drum.presetHouse,
        trap: drum.presetTrap,
        breakbeat: drum.presetBreakbeat,
        minimal: drum.presetMinimal,
      };
      return labels[preset] || preset;
    },
    [drum]
  );

  return (
    <div className="drum-machine">
      {/* Transport Controls */}
      <div className="drum-transport">
        <div className="drum-transport-controls">
          <button
            className={cn('drum-btn', isPlaying && 'drum-btn--active')}
            onClick={play}
            aria-label={isPlaying ? drum.pause : drum.play}
          >
            {isPlaying ? <PauseIcon /> : <PlayIcon />}
            <span>{isPlaying ? drum.pause : drum.play}</span>
          </button>
          <button
            className="drum-btn"
            onClick={stop}
            aria-label={drum.stop}
          >
            <StopIcon />
            <span>{drum.stop}</span>
          </button>
          <button
            className="drum-btn"
            onClick={clear}
            aria-label={drum.clear}
          >
            <ClearIcon />
            <span>{drum.clear}</span>
          </button>
          <button
            className="drum-btn drum-btn--export"
            onClick={handleExportMidi}
            aria-label={drum.exportMidi}
          >
            <DownloadIcon />
            <span>{drum.exportMidi}</span>
          </button>
          <button
            className="drum-btn drum-btn--import"
            onClick={handleImportClick}
            aria-label={drum.importMidi}
          >
            <UploadIcon />
            <span>{drum.importMidi}</span>
          </button>
          <input
            ref={fileInputRef}
            type="file"
            accept=".mid,.midi,audio/midi,audio/x-midi"
            onChange={handleFileChange}
            style={{ display: 'none' }}
            aria-hidden="true"
          />
        </div>

        <div className="drum-tempo">
          <span className="drum-tempo-label">{drum.tempo}</span>
          <input
            type="range"
            className="drum-slider"
            min={TEMPO_RANGE.MIN}
            max={TEMPO_RANGE.MAX}
            value={tempo}
            onChange={handleTempoChange}
            aria-label={drum.tempo}
          />
          <span className="drum-tempo-value">{tempo} BPM</span>
        </div>
      </div>

      {/* Sequencer Grid */}
      <div
        className="drum-sequencer"
        onMouseUp={handleDragEnd}
        onMouseLeave={handleDragEnd}
        onTouchMove={handleTouchMove}
        onTouchEnd={handleDragEnd}
      >
        {INSTRUMENTS.map((inst) => (
          <div key={inst} className="drum-track">
            <div className="drum-track-info">
              <div className="drum-track-label">{getInstrumentLabel(inst)}</div>
              <div className="drum-track-volume">
                <input
                  type="range"
                  className="drum-volume-slider"
                  min={VOLUME_RANGE.MIN}
                  max={VOLUME_RANGE.MAX}
                  value={volumes[inst]}
                  onChange={(e) => handleVolumeChange(inst, parseInt(e.target.value, 10))}
                  aria-label={`${getInstrumentLabel(inst)} ${drum.volume}`}
                />
                <span className="drum-volume-value">{volumes[inst]}</span>
              </div>
            </div>
            <div className="drum-track-steps">
              {Array.from({ length: STEPS }).map((_, step) => {
                const velocity = pattern[inst][step];
                const isActive = velocity > 0;
                // Opacity: min 0.3 at velocity 10, max 1 at velocity 100
                const opacity = isActive ? 0.3 + (velocity / VELOCITY.MAX) * 0.7 : 1;
                return (
                  <button
                    key={step}
                    className={cn(
                      'drum-step',
                      isActive && 'drum-step--active',
                      isPlaying && currentStep === step && 'drum-step--playing'
                    )}
                    style={isActive ? { opacity } : undefined}
                    data-instrument={inst}
                    data-step={step}
                    onMouseDown={(e) => {
                      e.preventDefault();
                      handleStepMouseDown(inst, step, e.clientY);
                    }}
                    onMouseEnter={() => handleStepMouseEnter(inst, step)}
                    onTouchStart={(e) => {
                      e.preventDefault();
                      const touch = e.touches[0];
                      handleStepMouseDown(inst, step, touch.clientY);
                    }}
                    aria-label={`${getInstrumentLabel(inst)} ${drum.step} ${step + 1}${isActive ? ` (${velocity}%)` : ''}`}
                    aria-pressed={isActive}
                  />
                );
              })}
            </div>
          </div>
        ))}
      </div>

      {/* Presets */}
      <div className="drum-presets">
        <span className="drum-presets-label">{drum.presets}</span>
        <div className="drum-presets-buttons">
          {Object.keys(PRESETS).map((preset) => (
            <button
              key={preset}
              className="drum-preset-btn"
              onClick={() => loadPreset(preset)}
            >
              {getPresetLabel(preset)}
            </button>
          ))}
        </div>
      </div>

      {/* Status Message */}
      {statusMessage && (
        <div className={cn('drum-status', `drum-status--${statusMessage.type}`)}>
          {statusMessage.text}
        </div>
      )}
    </div>
  );
});

DrumMachine.displayName = 'DrumMachine';
