// src/components/Footer.tsx
import { memo } from 'react';
import { Link } from 'react-router-dom';
import { useTranslations } from '../i18n';

/**
 * Footer component with menu links and copyright
 */
export const Footer = memo(function Footer() {
  const t = useTranslations();

  return (
    <footer className="footer">
      {/* Footer Menu */}
      <nav className="footer-menu" aria-label="Footer navigation">
        <Link to="/privacy" className="footer-link">
          {t.common.footer.privacy}
        </Link>
        <Link to="/terms" className="footer-link">
          {t.common.footer.terms}
        </Link>
        <a
          href="https://github.com/soundbluemusic/tools"
          className="footer-link"
          target="_blank"
          rel="noopener noreferrer"
        >
          {t.common.footer.github}
        </a>
        <Link to="/sitemap" className="footer-link">
          {t.common.footer.sitemap}
        </Link>
        <Link to="/opensource" className="footer-link">
          {t.common.footer.opensource}
        </Link>
        <Link to="/tools-used" className="footer-link">
          {t.common.footer.toolsUsed}
        </Link>
      </nav>

      {/* Copyright */}
      <p className="footer-copyright">
        © SoundBlueMusic. MIT License
      </p>
    </footer>
  );
});

Footer.displayName = 'Footer';

// src/lib/components/Footer.svelte
<script lang="ts">
  import { t } from '$lib/stores';
</script>

<footer class="footer">
  <nav class="footer-menu">
    <a href="/privacy" class="footer-link">{$t.common.footer.privacy}</a>
    <a href="/terms" class="footer-link">{$t.common.footer.terms}</a>
    <a href="/sitemap" class="footer-link">{$t.common.footer.sitemap}</a>
    <a href="/opensource" class="footer-link">{$t.common.footer.opensource}</a>
    <a href="/tools-used" class="footer-link">{$t.common.footer.toolsUsed}</a>
    <a href="https://github.com/soundbluemusic/tools" target="_blank" rel="noopener noreferrer" class="footer-link">{$t.common.footer.github}</a>
  </nav>
  <p class="footer-copyright">© {new Date().getFullYear()} Productivity Tools</p>
</footer>
