// src/routes/metronome/+page.svelte
<script lang="ts">
  import PageLayout from '../../components/layout/PageLayout.svelte';
  import MetronomePlayer from '../../apps/metronome/components/MetronomePlayer.svelte';
  import ShareButton from '../../components/ShareButton.svelte';
  import { t } from '../../stores';

  $: metronome = $t.metronome;

  $: breadcrumb = [
    { label: { ko: '홈', en: 'Home' }, href: '/' },
    { label: { ko: '음악 도구', en: 'Music Tools' }, href: '/' },
    { label: { ko: metronome.title, en: metronome.title } },
  ];
</script>

<PageLayout
  title={metronome.title}
  description={metronome.description}
  {breadcrumb}
>
  <svelte:fragment slot="actions">
    <ShareButton title={metronome.title} description={metronome.description} />
  </svelte:fragment>

  <MetronomePlayer />
</PageLayout>

// _backup_react/src/pages/Metronome.tsx
import { memo, useMemo } from 'react';
import { PageLayout } from '../components/layout';
import { MetronomePlayer } from '../apps/metronome/components/MetronomePlayer';
import { ShareButton } from '../components/ShareButton';
import { EmbedButton } from '../components/EmbedButton';
import { useTranslations } from '../i18n/context';
import { useSEO } from '../hooks';

/**
 * Metronome Tool Page
 */
const Metronome = memo(function Metronome() {
  const { metronome } = useTranslations();

  // Dynamic SEO for Metronome page
  useSEO({
    title: metronome.seo.title,
    description: metronome.seo.description,
    keywords: metronome.seo.keywords,
    canonicalPath: '/metronome',
  });

  // Breadcrumb items
  const breadcrumb = useMemo(
    () => [
      { label: { ko: '홈', en: 'Home' }, href: '/' },
      { label: { ko: '음악 도구', en: 'Music Tools' }, href: '/' },
      { label: { ko: metronome.title, en: metronome.title } },
    ],
    [metronome.title]
  );

  return (
    <PageLayout
      title={metronome.title}
      description={metronome.description}
      breadcrumb={breadcrumb}
      actions={
        <>
          <EmbedButton title={metronome.title} defaultWidth={400} defaultHeight={500} />
          <ShareButton title={metronome.title} description={metronome.description} />
        </>
      }
    >
      <MetronomePlayer />
    </PageLayout>
  );
});

Metronome.displayName = 'Metronome';

export default Metronome;
