// src/standalone/metronome/App.tsx
import { useState, useEffect, useCallback } from 'react';
import { MetronomePlayer } from './MetronomePlayer';
import { detectLanguage, getTranslations, type Language } from './i18n';

/**
 * Standalone Metronome App
 * Self-contained React app for metronome functionality
 */
export default function App() {
  const [language, setLanguage] = useState<Language>(detectLanguage);
  const [theme, setTheme] = useState<'light' | 'dark'>(() => {
    const stored = localStorage.getItem('metronome-theme');
    if (stored === 'dark' || stored === 'light') return stored;
    return window.matchMedia('(prefers-color-scheme: dark)').matches
      ? 'dark'
      : 'light';
  });

  const t = getTranslations(language);

  // Theme toggle
  const toggleTheme = useCallback(() => {
    setTheme((prev) => {
      const next = prev === 'light' ? 'dark' : 'light';
      localStorage.setItem('metronome-theme', next);
      document.documentElement.setAttribute('data-theme', next);
      return next;
    });
  }, []);

  // Language toggle
  const toggleLanguage = useCallback(() => {
    setLanguage((prev) => {
      const next = prev === 'ko' ? 'en' : 'ko';
      localStorage.setItem('metronome-lang', next);
      return next;
    });
  }, []);

  // Set initial theme attribute
  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme);
  }, [theme]);

  return (
    <div className="standalone-app">
      {/* Header with controls */}
      <header className="standalone-header">
        <h1 className="standalone-title">{t.title}</h1>
        <div className="standalone-controls">
          {/* Language Toggle */}
          <button
            onClick={toggleLanguage}
            className="standalone-btn"
            title={t.language}
            aria-label={t.language}
          >
            {language === 'ko' ? 'EN' : '한국어'}
          </button>

          {/* Theme Toggle */}
          <button
            onClick={toggleTheme}
            className="standalone-btn"
            title={theme === 'light' ? t.darkMode : t.lightMode}
            aria-label={theme === 'light' ? t.darkMode : t.lightMode}
          >
            {theme === 'light' ? (
              <svg
                width="20"
                height="20"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
              >
                <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
              </svg>
            ) : (
              <svg
                width="20"
                height="20"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
              >
                <circle cx="12" cy="12" r="5" />
                <line x1="12" y1="1" x2="12" y2="3" />
                <line x1="12" y1="21" x2="12" y2="23" />
                <line x1="4.22" y1="4.22" x2="5.64" y2="5.64" />
                <line x1="18.36" y1="18.36" x2="19.78" y2="19.78" />
                <line x1="1" y1="12" x2="3" y2="12" />
                <line x1="21" y1="12" x2="23" y2="12" />
                <line x1="4.22" y1="19.78" x2="5.64" y2="18.36" />
                <line x1="18.36" y1="5.64" x2="19.78" y2="4.22" />
              </svg>
            )}
          </button>
        </div>
      </header>

      {/* Metronome */}
      <main className="standalone-main">
        <MetronomePlayer translations={t} />
      </main>
    </div>
  );
}

// src/standalone/qr/App.tsx
import { type Component, createSignal, createEffect, Show } from 'solid-js';
import { QRGenerator } from '../../apps/qr/components/QRGenerator';
import { detectLanguage, getTranslations, type Language } from './i18n';

/**
 * Standalone QR Code Generator App
 * Self-contained Solid.js app for QR code generation
 */
const App: Component = () => {
  const [language, setLanguage] = createSignal<Language>(detectLanguage());
  const [theme, setTheme] = createSignal<'light' | 'dark'>(() => {
    const stored = localStorage.getItem('qr-theme');
    if (stored === 'dark' || stored === 'light') return stored;
    return window.matchMedia('(prefers-color-scheme: dark)').matches
      ? 'dark'
      : 'light';
  });

  const t = () => getTranslations(language());

  // Theme toggle
  const toggleTheme = () => {
    setTheme((prev) => {
      const next = prev === 'light' ? 'dark' : 'light';
      localStorage.setItem('qr-theme', next);
      document.documentElement.setAttribute('data-theme', next);
      return next;
    });
  };

  // Language toggle
  const toggleLanguage = () => {
    setLanguage((prev) => {
      const next = prev === 'ko' ? 'en' : 'ko';
      localStorage.setItem('qr-lang', next);
      return next;
    });
  };

  // Set initial theme attribute
  createEffect(() => {
    document.documentElement.setAttribute('data-theme', theme());
  });

  return (
    <div class="standalone-app">
      {/* Header with controls */}
      <header class="standalone-header">
        <h1 class="standalone-title">{t().title}</h1>
        <div class="standalone-controls">
          {/* Language Toggle */}
          <button
            onClick={toggleLanguage}
            class="standalone-btn"
            title={t().language}
            aria-label={t().language}
          >
            {language() === 'ko' ? 'EN' : '한국어'}
          </button>

          {/* Theme Toggle */}
          <button
            onClick={toggleTheme}
            class="standalone-btn"
            title={theme() === 'light' ? t().darkMode : t().lightMode}
            aria-label={theme() === 'light' ? t().darkMode : t().lightMode}
          >
            <Show
              when={theme() === 'light'}
              fallback={
                <svg
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                >
                  <circle cx="12" cy="12" r="5" />
                  <line x1="12" y1="1" x2="12" y2="3" />
                  <line x1="12" y1="21" x2="12" y2="23" />
                  <line x1="4.22" y1="4.22" x2="5.64" y2="5.64" />
                  <line x1="18.36" y1="18.36" x2="19.78" y2="19.78" />
                  <line x1="1" y1="12" x2="3" y2="12" />
                  <line x1="21" y1="12" x2="23" y2="12" />
                  <line x1="4.22" y1="19.78" x2="5.64" y2="18.36" />
                  <line x1="18.36" y1="5.64" x2="19.78" y2="4.22" />
                </svg>
              }
            >
              <svg
                width="20"
                height="20"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
              >
                <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
              </svg>
            </Show>
          </button>
        </div>
      </header>

      {/* QR Generator */}
      <main class="standalone-main">
        <QRGenerator translations={t()} />
      </main>
    </div>
  );
};

export default App;
