// src/lib/components/ui/Button.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { HTMLButtonAttributes } from 'svelte/elements';

  interface Props extends HTMLButtonAttributes {
    variant?: 'primary' | 'secondary' | 'ghost' | 'outline';
    size?: 'sm' | 'md' | 'lg';
    fullWidth?: boolean;
    loading?: boolean;
    children: Snippet;
  }

  let {
    variant = 'primary',
    size = 'md',
    fullWidth = false,
    loading = false,
    children,
    class: className = '',
    ...restProps
  }: Props = $props();

  const classes = $derived(
    [
      'btn',
      `btn--${variant}`,
      `btn--${size}`,
      fullWidth && 'btn--full-width',
      loading && 'btn--loading',
      className
    ]
      .filter(Boolean)
      .join(' ')
  );
</script>

<button class={classes} disabled={loading || restProps.disabled} {...restProps}>
  {#if loading}
    <span class="btn-spinner"></span>
  {/if}
  {@render children()}
</button>

// src/components/ui/Button.tsx
import { memo, forwardRef, type ButtonHTMLAttributes, type ReactNode } from 'react';
import { cn } from '../../utils';

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  /** Button variant */
  variant?: 'primary' | 'secondary' | 'ghost' | 'outline';
  /** Button size */
  size?: 'sm' | 'md' | 'lg';
  /** Full width button */
  fullWidth?: boolean;
  /** Loading state */
  loading?: boolean;
  /** Start icon */
  startIcon?: ReactNode;
  /** End icon */
  endIcon?: ReactNode;
}

/**
 * Button component with variants and loading state
 */
export const Button = memo(
  forwardRef<HTMLButtonElement, ButtonProps>(function Button(
    {
      variant = 'primary',
      size = 'md',
      fullWidth = false,
      loading = false,
      startIcon,
      endIcon,
      disabled,
      className,
      children,
      ...props
    },
    ref
  ) {
    const variantClass = {
      primary: 'btn--primary',
      secondary: 'btn--secondary',
      ghost: 'btn--ghost',
      outline: 'btn--outline',
    }[variant];

    const sizeClass = {
      sm: 'btn--sm',
      md: 'btn--md',
      lg: 'btn--lg',
    }[size];

    return (
      <button
        ref={ref}
        className={cn(
          'btn',
          variantClass,
          sizeClass,
          fullWidth && 'btn--full-width',
          loading && 'btn--loading',
          className
        )}
        disabled={disabled || loading}
        {...props}
      >
        {loading && <span className="btn-spinner" aria-hidden="true" />}
        {!loading && startIcon && (
          <span className="btn-icon btn-icon--start">{startIcon}</span>
        )}
        <span className="btn-content">{children}</span>
        {!loading && endIcon && (
          <span className="btn-icon btn-icon--end">{endIcon}</span>
        )}
      </button>
    );
  })
);

Button.displayName = 'Button';
